#红锋利
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"红锋利等级"=1}] ~~~ execute @a[scores={"分队"=1},x=-63,y=171,z=-63,dx=126,dy=33,dz=126,tag=!have_upgraded_sword_sharpness_i] ~~~ function shop_purchase/clear_items/clear_wooden_sword
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"红锋利等级"=1}] ~~~ execute @a[scores={"分队"=1},x=-63,y=171,z=-63,dx=126,dy=33,dz=126,tag=!have_upgraded_sword_sharpness_i] ~~~ function shop_purchase/clear_items/clear_stone_sword
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"红锋利等级"=1}] ~~~ execute @a[scores={"分队"=1},x=-63,y=171,z=-63,dx=126,dy=33,dz=126,tag=!have_upgraded_sword_sharpness_i] ~~~ function shop_purchase/clear_items/clear_iron_sword
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"红锋利等级"=1}] ~~~ execute @a[scores={"分队"=1},x=-63,y=171,z=-63,dx=126,dy=33,dz=126,tag=!have_upgraded_sword_sharpness_i] ~~~ function shop_purchase/clear_items/clear_diamond_sword
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"红锋利等级"=1}] ~~~ execute @a[scores={"分队"=1,"剑等级"=1},x=-63,y=171,z=-63,dx=126,dy=33,dz=126,tag=!have_upgraded_sword_sharpness_i] ~~~ function shop_purchase/give_items/give_wooden_sword_sharpness_i
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"红锋利等级"=1}] ~~~ execute @a[scores={"分队"=1,"剑等级"=2},x=-63,y=171,z=-63,dx=126,dy=33,dz=126,tag=!have_upgraded_sword_sharpness_i] ~~~ function shop_purchase/give_items/give_stone_sword_sharpness_i
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"红锋利等级"=1}] ~~~ execute @a[scores={"分队"=1,"剑等级"=3},x=-63,y=171,z=-63,dx=126,dy=33,dz=126,tag=!have_upgraded_sword_sharpness_i] ~~~ function shop_purchase/give_items/give_iron_sword_sharpness_i
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"红锋利等级"=1}] ~~~ execute @a[scores={"分队"=1,"剑等级"=4},x=-63,y=171,z=-63,dx=126,dy=33,dz=126,tag=!have_upgraded_sword_sharpness_i] ~~~ function shop_purchase/give_items/give_diamond_sword_sharpness_i
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"红锋利等级"=1}] ~~~ tag @a[scores={"分队"=1}] add have_upgraded_sword_sharpness_i
#蓝锋利
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"蓝锋利等级"=1}] ~~~ execute @a[scores={"分队"=2},x=-63,y=171,z=-63,dx=126,dy=33,dz=126,tag=!have_upgraded_sword_sharpness_i] ~~~ function shop_purchase/clear_items/clear_wooden_sword
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"蓝锋利等级"=1}] ~~~ execute @a[scores={"分队"=2},x=-63,y=171,z=-63,dx=126,dy=33,dz=126,tag=!have_upgraded_sword_sharpness_i] ~~~ function shop_purchase/clear_items/clear_stone_sword
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"蓝锋利等级"=1}] ~~~ execute @a[scores={"分队"=2},x=-63,y=171,z=-63,dx=126,dy=33,dz=126,tag=!have_upgraded_sword_sharpness_i] ~~~ function shop_purchase/clear_items/clear_iron_sword
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"蓝锋利等级"=1}] ~~~ execute @a[scores={"分队"=2},x=-63,y=171,z=-63,dx=126,dy=33,dz=126,tag=!have_upgraded_sword_sharpness_i] ~~~ function shop_purchase/clear_items/clear_diamond_sword
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"蓝锋利等级"=1}] ~~~ execute @a[scores={"分队"=2,"剑等级"=1},x=-63,y=171,z=-63,dx=126,dy=33,dz=126,tag=!have_upgraded_sword_sharpness_i] ~~~ function shop_purchase/give_items/give_wooden_sword_sharpness_i
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"蓝锋利等级"=1}] ~~~ execute @a[scores={"分队"=2,"剑等级"=2},x=-63,y=171,z=-63,dx=126,dy=33,dz=126,tag=!have_upgraded_sword_sharpness_i] ~~~ function shop_purchase/give_items/give_stone_sword_sharpness_i
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"蓝锋利等级"=1}] ~~~ execute @a[scores={"分队"=2,"剑等级"=3},x=-63,y=171,z=-63,dx=126,dy=33,dz=126,tag=!have_upgraded_sword_sharpness_i] ~~~ function shop_purchase/give_items/give_iron_sword_sharpness_i
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"蓝锋利等级"=1}] ~~~ execute @a[scores={"分队"=2,"剑等级"=4},x=-63,y=171,z=-63,dx=126,dy=33,dz=126,tag=!have_upgraded_sword_sharpness_i] ~~~ function shop_purchase/give_items/give_diamond_sword_sharpness_i
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"蓝锋利等级"=1}] ~~~ tag @a[scores={"分队"=2}] add have_upgraded_sword_sharpness_i
#黄锋利
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"黄锋利等级"=1}] ~~~ execute @a[scores={"分队"=3},x=-63,y=171,z=-63,dx=126,dy=33,dz=126,tag=!have_upgraded_sword_sharpness_i] ~~~ function shop_purchase/clear_items/clear_wooden_sword
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"黄锋利等级"=1}] ~~~ execute @a[scores={"分队"=3},x=-63,y=171,z=-63,dx=126,dy=33,dz=126,tag=!have_upgraded_sword_sharpness_i] ~~~ function shop_purchase/clear_items/clear_stone_sword
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"黄锋利等级"=1}] ~~~ execute @a[scores={"分队"=3},x=-63,y=171,z=-63,dx=126,dy=33,dz=126,tag=!have_upgraded_sword_sharpness_i] ~~~ function shop_purchase/clear_items/clear_iron_sword
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"黄锋利等级"=1}] ~~~ execute @a[scores={"分队"=3},x=-63,y=171,z=-63,dx=126,dy=33,dz=126,tag=!have_upgraded_sword_sharpness_i] ~~~ function shop_purchase/clear_items/clear_diamond_sword
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"黄锋利等级"=1}] ~~~ execute @a[scores={"分队"=3,"剑等级"=1},x=-63,y=171,z=-63,dx=126,dy=33,dz=126,tag=!have_upgraded_sword_sharpness_i] ~~~ function shop_purchase/give_items/give_wooden_sword_sharpness_i
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"黄锋利等级"=1}] ~~~ execute @a[scores={"分队"=3,"剑等级"=2},x=-63,y=171,z=-63,dx=126,dy=33,dz=126,tag=!have_upgraded_sword_sharpness_i] ~~~ function shop_purchase/give_items/give_stone_sword_sharpness_i
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"黄锋利等级"=1}] ~~~ execute @a[scores={"分队"=3,"剑等级"=3},x=-63,y=171,z=-63,dx=126,dy=33,dz=126,tag=!have_upgraded_sword_sharpness_i] ~~~ function shop_purchase/give_items/give_iron_sword_sharpness_i
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"黄锋利等级"=1}] ~~~ execute @a[scores={"分队"=3,"剑等级"=4},x=-63,y=171,z=-63,dx=126,dy=33,dz=126,tag=!have_upgraded_sword_sharpness_i] ~~~ function shop_purchase/give_items/give_diamond_sword_sharpness_i
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"黄锋利等级"=1}] ~~~ tag @a[scores={"分队"=3}] add have_upgraded_sword_sharpness_i
#绿锋利
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"绿锋利等级"=1}] ~~~ execute @a[scores={"分队"=4},x=-63,y=171,z=-63,dx=126,dy=33,dz=126,tag=!have_upgraded_sword_sharpness_i] ~~~ function shop_purchase/clear_items/clear_wooden_sword
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"绿锋利等级"=1}] ~~~ execute @a[scores={"分队"=4},x=-63,y=171,z=-63,dx=126,dy=33,dz=126,tag=!have_upgraded_sword_sharpness_i] ~~~ function shop_purchase/clear_items/clear_stone_sword
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"绿锋利等级"=1}] ~~~ execute @a[scores={"分队"=4},x=-63,y=171,z=-63,dx=126,dy=33,dz=126,tag=!have_upgraded_sword_sharpness_i] ~~~ function shop_purchase/clear_items/clear_iron_sword
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"绿锋利等级"=1}] ~~~ execute @a[scores={"分队"=4},x=-63,y=171,z=-63,dx=126,dy=33,dz=126,tag=!have_upgraded_sword_sharpness_i] ~~~ function shop_purchase/clear_items/clear_diamond_sword
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"绿锋利等级"=1}] ~~~ execute @a[scores={"分队"=4,"剑等级"=1},x=-63,y=171,z=-63,dx=126,dy=33,dz=126,tag=!have_upgraded_sword_sharpness_i] ~~~ function shop_purchase/give_items/give_wooden_sword_sharpness_i
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"绿锋利等级"=1}] ~~~ execute @a[scores={"分队"=4,"剑等级"=2},x=-63,y=171,z=-63,dx=126,dy=33,dz=126,tag=!have_upgraded_sword_sharpness_i] ~~~ function shop_purchase/give_items/give_stone_sword_sharpness_i
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"绿锋利等级"=1}] ~~~ execute @a[scores={"分队"=4,"剑等级"=3},x=-63,y=171,z=-63,dx=126,dy=33,dz=126,tag=!have_upgraded_sword_sharpness_i] ~~~ function shop_purchase/give_items/give_iron_sword_sharpness_i
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"绿锋利等级"=1}] ~~~ execute @a[scores={"分队"=4,"剑等级"=4},x=-63,y=171,z=-63,dx=126,dy=33,dz=126,tag=!have_upgraded_sword_sharpness_i] ~~~ function shop_purchase/give_items/give_diamond_sword_sharpness_i
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"绿锋利等级"=1}] ~~~ tag @a[scores={"分队"=4}] add have_upgraded_sword_sharpness_i