#红锋利
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"红锋利等级"=1}] ~~~ tag @a[scores={"分队"=1},x=-63,y=171,z=-63,dx=126,dy=33,dz=126,tag=!have_upgraded_sword_sharpnessI] add clear_wooden_sword
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"红锋利等级"=1}] ~~~ tag @a[scores={"分队"=1},x=-63,y=171,z=-63,dx=126,dy=33,dz=126,tag=!have_upgraded_sword_sharpnessI] add clear_stone_sword
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"红锋利等级"=1}] ~~~ tag @a[scores={"分队"=1},x=-63,y=171,z=-63,dx=126,dy=33,dz=126,tag=!have_upgraded_sword_sharpnessI] add clear_iron_sword
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"红锋利等级"=1}] ~~~ tag @a[scores={"分队"=1},x=-63,y=171,z=-63,dx=126,dy=33,dz=126,tag=!have_upgraded_sword_sharpnessI] add clear_diamond_sword
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"红锋利等级"=1}] ~~~ tag @a[scores={"分队"=1,"剑等级"=1},x=-63,y=171,z=-63,dx=126,dy=33,dz=126,tag=!have_upgraded_sword_sharpnessI] add give_wooden_sword_sharpnessI
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"红锋利等级"=1}] ~~~ tag @a[scores={"分队"=1,"剑等级"=2},x=-63,y=171,z=-63,dx=126,dy=33,dz=126,tag=!have_upgraded_sword_sharpnessI] add give_stone_sword_sharpnessI
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"红锋利等级"=1}] ~~~ tag @a[scores={"分队"=1,"剑等级"=3},x=-63,y=171,z=-63,dx=126,dy=33,dz=126,tag=!have_upgraded_sword_sharpnessI] add give_iron_sword_sharpnessI
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"红锋利等级"=1}] ~~~ tag @a[scores={"分队"=1,"剑等级"=4},x=-63,y=171,z=-63,dx=126,dy=33,dz=126,tag=!have_upgraded_sword_sharpnessI] add give_diamond_sword_sharpnessI
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"红锋利等级"=1}] ~~~ tag @a[scores={"分队"=1}] add have_upgraded_sword_sharpnessI
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"红锋利等级"=2}] ~~~ tag @a[scores={"分队"=1},x=-63,y=171,z=-63,dx=126,dy=33,dz=126,tag=!have_upgraded_sword_sharpnessII] add clear_wooden_sword_sharpnessI
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"红锋利等级"=2}] ~~~ tag @a[scores={"分队"=1},x=-63,y=171,z=-63,dx=126,dy=33,dz=126,tag=!have_upgraded_sword_sharpnessII] add clear_stone_sword_sharpnessI
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"红锋利等级"=2}] ~~~ tag @a[scores={"分队"=1},x=-63,y=171,z=-63,dx=126,dy=33,dz=126,tag=!have_upgraded_sword_sharpnessII] add clear_iron_sword_sharpnessI
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"红锋利等级"=2}] ~~~ tag @a[scores={"分队"=1},x=-63,y=171,z=-63,dx=126,dy=33,dz=126,tag=!have_upgraded_sword_sharpnessII] add clear_diamond_sword_sharpnessI
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"红锋利等级"=2}] ~~~ tag @a[scores={"分队"=1,"剑等级"=1},x=-63,y=171,z=-63,dx=126,dy=33,dz=126,tag=!have_upgraded_sword_sharpnessII] add give_wooden_sword_sharpnessII
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"红锋利等级"=2}] ~~~ tag @a[scores={"分队"=1,"剑等级"=2},x=-63,y=171,z=-63,dx=126,dy=33,dz=126,tag=!have_upgraded_sword_sharpnessII] add give_stone_sword_sharpnessII
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"红锋利等级"=2}] ~~~ tag @a[scores={"分队"=1,"剑等级"=3},x=-63,y=171,z=-63,dx=126,dy=33,dz=126,tag=!have_upgraded_sword_sharpnessII] add give_iron_sword_sharpnessII
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"红锋利等级"=2}] ~~~ tag @a[scores={"分队"=1,"剑等级"=4},x=-63,y=171,z=-63,dx=126,dy=33,dz=126,tag=!have_upgraded_sword_sharpnessII] add give_diamond_sword_sharpnessII
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"红锋利等级"=2}] ~~~ tag @a[scores={"分队"=1}] add have_upgraded_sword_sharpnessII
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"红锋利等级"=3}] ~~~ tag @a[scores={"分队"=1},x=-63,y=171,z=-63,dx=126,dy=33,dz=126,tag=!have_upgraded_sword_sharpnessIII] add clear_wooden_sword_sharpnessII
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"红锋利等级"=3}] ~~~ tag @a[scores={"分队"=1},x=-63,y=171,z=-63,dx=126,dy=33,dz=126,tag=!have_upgraded_sword_sharpnessIII] add clear_stone_sword_sharpnessII
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"红锋利等级"=3}] ~~~ tag @a[scores={"分队"=1},x=-63,y=171,z=-63,dx=126,dy=33,dz=126,tag=!have_upgraded_sword_sharpnessIII] add clear_iron_sword_sharpnessII
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"红锋利等级"=3}] ~~~ tag @a[scores={"分队"=1},x=-63,y=171,z=-63,dx=126,dy=33,dz=126,tag=!have_upgraded_sword_sharpnessIII] add clear_diamond_sword_sharpnessII
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"红锋利等级"=3}] ~~~ tag @a[scores={"分队"=1,"剑等级"=1},x=-63,y=171,z=-63,dx=126,dy=33,dz=126,tag=!have_upgraded_sword_sharpnessIII] add give_wooden_sword_sharpnessIII
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"红锋利等级"=3}] ~~~ tag @a[scores={"分队"=1,"剑等级"=2},x=-63,y=171,z=-63,dx=126,dy=33,dz=126,tag=!have_upgraded_sword_sharpnessIII] add give_stone_sword_sharpnessIII
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"红锋利等级"=3}] ~~~ tag @a[scores={"分队"=1,"剑等级"=3},x=-63,y=171,z=-63,dx=126,dy=33,dz=126,tag=!have_upgraded_sword_sharpnessIII] add give_iron_sword_sharpnessIII
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"红锋利等级"=3}] ~~~ tag @a[scores={"分队"=1,"剑等级"=4},x=-63,y=171,z=-63,dx=126,dy=33,dz=126,tag=!have_upgraded_sword_sharpnessIII] add give_diamond_sword_sharpnessIII
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"红锋利等级"=3}] ~~~ tag @a[scores={"分队"=1}] add have_upgraded_sword_sharpnessIII
#蓝锋利
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"蓝锋利等级"=1}] ~~~ tag @a[scores={"分队"=2},x=-63,y=171,z=-63,dx=126,dy=33,dz=126,tag=!have_upgraded_sword_sharpnessI] add clear_wooden_sword
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"蓝锋利等级"=1}] ~~~ tag @a[scores={"分队"=2},x=-63,y=171,z=-63,dx=126,dy=33,dz=126,tag=!have_upgraded_sword_sharpnessI] add clear_stone_sword
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"蓝锋利等级"=1}] ~~~ tag @a[scores={"分队"=2},x=-63,y=171,z=-63,dx=126,dy=33,dz=126,tag=!have_upgraded_sword_sharpnessI] add clear_iron_sword
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"蓝锋利等级"=1}] ~~~ tag @a[scores={"分队"=2},x=-63,y=171,z=-63,dx=126,dy=33,dz=126,tag=!have_upgraded_sword_sharpnessI] add clear_diamond_sword
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"蓝锋利等级"=1}] ~~~ tag @a[scores={"分队"=2,"剑等级"=1},x=-63,y=171,z=-63,dx=126,dy=33,dz=126,tag=!have_upgraded_sword_sharpnessI] add give_wooden_sword_sharpnessI
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"蓝锋利等级"=1}] ~~~ tag @a[scores={"分队"=2,"剑等级"=2},x=-63,y=171,z=-63,dx=126,dy=33,dz=126,tag=!have_upgraded_sword_sharpnessI] add give_stone_sword_sharpnessI
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"蓝锋利等级"=1}] ~~~ tag @a[scores={"分队"=2,"剑等级"=3},x=-63,y=171,z=-63,dx=126,dy=33,dz=126,tag=!have_upgraded_sword_sharpnessI] add give_iron_sword_sharpnessI
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"蓝锋利等级"=1}] ~~~ tag @a[scores={"分队"=2,"剑等级"=4},x=-63,y=171,z=-63,dx=126,dy=33,dz=126,tag=!have_upgraded_sword_sharpnessI] add give_diamond_sword_sharpnessI
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"蓝锋利等级"=1}] ~~~ tag @a[scores={"分队"=2}] add have_upgraded_sword_sharpnessI
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"蓝锋利等级"=2}] ~~~ tag @a[scores={"分队"=2},x=-63,y=171,z=-63,dx=126,dy=33,dz=126,tag=!have_upgraded_sword_sharpnessII] add clear_wooden_sword_sharpnessI
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"蓝锋利等级"=2}] ~~~ tag @a[scores={"分队"=2},x=-63,y=171,z=-63,dx=126,dy=33,dz=126,tag=!have_upgraded_sword_sharpnessII] add clear_stone_sword_sharpnessI
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"蓝锋利等级"=2}] ~~~ tag @a[scores={"分队"=2},x=-63,y=171,z=-63,dx=126,dy=33,dz=126,tag=!have_upgraded_sword_sharpnessII] add clear_iron_sword_sharpnessI
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"蓝锋利等级"=2}] ~~~ tag @a[scores={"分队"=2},x=-63,y=171,z=-63,dx=126,dy=33,dz=126,tag=!have_upgraded_sword_sharpnessII] add clear_diamond_sword_sharpnessI
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"蓝锋利等级"=2}] ~~~ tag @a[scores={"分队"=2,"剑等级"=1},x=-63,y=171,z=-63,dx=126,dy=33,dz=126,tag=!have_upgraded_sword_sharpnessII] add give_wooden_sword_sharpnessII
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"蓝锋利等级"=2}] ~~~ tag @a[scores={"分队"=2,"剑等级"=2},x=-63,y=171,z=-63,dx=126,dy=33,dz=126,tag=!have_upgraded_sword_sharpnessII] add give_stone_sword_sharpnessII
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"蓝锋利等级"=2}] ~~~ tag @a[scores={"分队"=2,"剑等级"=3},x=-63,y=171,z=-63,dx=126,dy=33,dz=126,tag=!have_upgraded_sword_sharpnessII] add give_iron_sword_sharpnessII
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"蓝锋利等级"=2}] ~~~ tag @a[scores={"分队"=2,"剑等级"=4},x=-63,y=171,z=-63,dx=126,dy=33,dz=126,tag=!have_upgraded_sword_sharpnessII] add give_diamond_sword_sharpnessII
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"蓝锋利等级"=2}] ~~~ tag @a[scores={"分队"=2}] add have_upgraded_sword_sharpnessII
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"蓝锋利等级"=3}] ~~~ tag @a[scores={"分队"=2},x=-63,y=171,z=-63,dx=126,dy=33,dz=126,tag=!have_upgraded_sword_sharpnessIII] add clear_wooden_sword_sharpnessII
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"蓝锋利等级"=3}] ~~~ tag @a[scores={"分队"=2},x=-63,y=171,z=-63,dx=126,dy=33,dz=126,tag=!have_upgraded_sword_sharpnessIII] add clear_stone_sword_sharpnessII
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"蓝锋利等级"=3}] ~~~ tag @a[scores={"分队"=2},x=-63,y=171,z=-63,dx=126,dy=33,dz=126,tag=!have_upgraded_sword_sharpnessIII] add clear_iron_sword_sharpnessII
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"蓝锋利等级"=3}] ~~~ tag @a[scores={"分队"=2},x=-63,y=171,z=-63,dx=126,dy=33,dz=126,tag=!have_upgraded_sword_sharpnessIII] add clear_diamond_sword_sharpnessII
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"蓝锋利等级"=3}] ~~~ tag @a[scores={"分队"=2,"剑等级"=1},x=-63,y=171,z=-63,dx=126,dy=33,dz=126,tag=!have_upgraded_sword_sharpnessIII] add give_wooden_sword_sharpnessIII
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"蓝锋利等级"=3}] ~~~ tag @a[scores={"分队"=2,"剑等级"=2},x=-63,y=171,z=-63,dx=126,dy=33,dz=126,tag=!have_upgraded_sword_sharpnessIII] add give_stone_sword_sharpnessIII
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"蓝锋利等级"=3}] ~~~ tag @a[scores={"分队"=2,"剑等级"=3},x=-63,y=171,z=-63,dx=126,dy=33,dz=126,tag=!have_upgraded_sword_sharpnessIII] add give_iron_sword_sharpnessIII
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"蓝锋利等级"=3}] ~~~ tag @a[scores={"分队"=2,"剑等级"=4},x=-63,y=171,z=-63,dx=126,dy=33,dz=126,tag=!have_upgraded_sword_sharpnessIII] add give_diamond_sword_sharpnessIII
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"蓝锋利等级"=3}] ~~~ tag @a[scores={"分队"=2}] add have_upgraded_sword_sharpnessIII
#黄锋利
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"黄锋利等级"=1}] ~~~ tag @a[scores={"分队"=3},x=-63,y=171,z=-63,dx=126,dy=33,dz=126,tag=!have_upgraded_sword_sharpnessI] add clear_wooden_sword
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"黄锋利等级"=1}] ~~~ tag @a[scores={"分队"=3},x=-63,y=171,z=-63,dx=126,dy=33,dz=126,tag=!have_upgraded_sword_sharpnessI] add clear_stone_sword
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"黄锋利等级"=1}] ~~~ tag @a[scores={"分队"=3},x=-63,y=171,z=-63,dx=126,dy=33,dz=126,tag=!have_upgraded_sword_sharpnessI] add clear_iron_sword
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"黄锋利等级"=1}] ~~~ tag @a[scores={"分队"=3},x=-63,y=171,z=-63,dx=126,dy=33,dz=126,tag=!have_upgraded_sword_sharpnessI] add clear_diamond_sword
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"黄锋利等级"=1}] ~~~ tag @a[scores={"分队"=3,"剑等级"=1},x=-63,y=171,z=-63,dx=126,dy=33,dz=126,tag=!have_upgraded_sword_sharpnessI] add give_wooden_sword_sharpnessI
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"黄锋利等级"=1}] ~~~ tag @a[scores={"分队"=3,"剑等级"=2},x=-63,y=171,z=-63,dx=126,dy=33,dz=126,tag=!have_upgraded_sword_sharpnessI] add give_stone_sword_sharpnessI
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"黄锋利等级"=1}] ~~~ tag @a[scores={"分队"=3,"剑等级"=3},x=-63,y=171,z=-63,dx=126,dy=33,dz=126,tag=!have_upgraded_sword_sharpnessI] add give_iron_sword_sharpnessI
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"黄锋利等级"=1}] ~~~ tag @a[scores={"分队"=3,"剑等级"=4},x=-63,y=171,z=-63,dx=126,dy=33,dz=126,tag=!have_upgraded_sword_sharpnessI] add give_diamond_sword_sharpnessI
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"黄锋利等级"=1}] ~~~ tag @a[scores={"分队"=3}] add have_upgraded_sword_sharpnessI
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"黄锋利等级"=2}] ~~~ tag @a[scores={"分队"=3},x=-63,y=171,z=-63,dx=126,dy=33,dz=126,tag=!have_upgraded_sword_sharpnessII] add clear_wooden_sword_sharpnessI
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"黄锋利等级"=2}] ~~~ tag @a[scores={"分队"=3},x=-63,y=171,z=-63,dx=126,dy=33,dz=126,tag=!have_upgraded_sword_sharpnessII] add clear_stone_sword_sharpnessI
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"黄锋利等级"=2}] ~~~ tag @a[scores={"分队"=3},x=-63,y=171,z=-63,dx=126,dy=33,dz=126,tag=!have_upgraded_sword_sharpnessII] add clear_iron_sword_sharpnessI
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"黄锋利等级"=2}] ~~~ tag @a[scores={"分队"=3},x=-63,y=171,z=-63,dx=126,dy=33,dz=126,tag=!have_upgraded_sword_sharpnessII] add clear_diamond_sword_sharpnessI
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"黄锋利等级"=2}] ~~~ tag @a[scores={"分队"=3,"剑等级"=1},x=-63,y=171,z=-63,dx=126,dy=33,dz=126,tag=!have_upgraded_sword_sharpnessII] add give_wooden_sword_sharpnessII
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"黄锋利等级"=2}] ~~~ tag @a[scores={"分队"=3,"剑等级"=2},x=-63,y=171,z=-63,dx=126,dy=33,dz=126,tag=!have_upgraded_sword_sharpnessII] add give_stone_sword_sharpnessII
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"黄锋利等级"=2}] ~~~ tag @a[scores={"分队"=3,"剑等级"=3},x=-63,y=171,z=-63,dx=126,dy=33,dz=126,tag=!have_upgraded_sword_sharpnessII] add give_iron_sword_sharpnessII
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"黄锋利等级"=2}] ~~~ tag @a[scores={"分队"=3,"剑等级"=4},x=-63,y=171,z=-63,dx=126,dy=33,dz=126,tag=!have_upgraded_sword_sharpnessII] add give_diamond_sword_sharpnessII
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"黄锋利等级"=2}] ~~~ tag @a[scores={"分队"=3}] add have_upgraded_sword_sharpnessII
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"黄锋利等级"=3}] ~~~ tag @a[scores={"分队"=3},x=-63,y=171,z=-63,dx=126,dy=33,dz=126,tag=!have_upgraded_sword_sharpnessIII] add clear_wooden_sword_sharpnessII
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"黄锋利等级"=3}] ~~~ tag @a[scores={"分队"=3},x=-63,y=171,z=-63,dx=126,dy=33,dz=126,tag=!have_upgraded_sword_sharpnessIII] add clear_stone_sword_sharpnessII
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"黄锋利等级"=3}] ~~~ tag @a[scores={"分队"=3},x=-63,y=171,z=-63,dx=126,dy=33,dz=126,tag=!have_upgraded_sword_sharpnessIII] add clear_iron_sword_sharpnessII
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"黄锋利等级"=3}] ~~~ tag @a[scores={"分队"=3},x=-63,y=171,z=-63,dx=126,dy=33,dz=126,tag=!have_upgraded_sword_sharpnessIII] add clear_diamond_sword_sharpnessII
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"黄锋利等级"=3}] ~~~ tag @a[scores={"分队"=3,"剑等级"=1},x=-63,y=171,z=-63,dx=126,dy=33,dz=126,tag=!have_upgraded_sword_sharpnessIII] add give_wooden_sword_sharpnessIII
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"黄锋利等级"=3}] ~~~ tag @a[scores={"分队"=3,"剑等级"=2},x=-63,y=171,z=-63,dx=126,dy=33,dz=126,tag=!have_upgraded_sword_sharpnessIII] add give_stone_sword_sharpnessIII
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"黄锋利等级"=3}] ~~~ tag @a[scores={"分队"=3,"剑等级"=3},x=-63,y=171,z=-63,dx=126,dy=33,dz=126,tag=!have_upgraded_sword_sharpnessIII] add give_iron_sword_sharpnessIII
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"黄锋利等级"=3}] ~~~ tag @a[scores={"分队"=3,"剑等级"=4},x=-63,y=171,z=-63,dx=126,dy=33,dz=126,tag=!have_upgraded_sword_sharpnessIII] add give_diamond_sword_sharpnessIII
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"黄锋利等级"=3}] ~~~ tag @a[scores={"分队"=3}] add have_upgraded_sword_sharpnessIII
#绿锋利
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"绿锋利等级"=1}] ~~~ tag @a[scores={"分队"=3},x=-63,y=171,z=-63,dx=126,dy=33,dz=126,tag=!have_upgraded_sword_sharpnessI] add clear_wooden_sword
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"绿锋利等级"=1}] ~~~ tag @a[scores={"分队"=3},x=-63,y=171,z=-63,dx=126,dy=33,dz=126,tag=!have_upgraded_sword_sharpnessI] add clear_stone_sword
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"绿锋利等级"=1}] ~~~ tag @a[scores={"分队"=3},x=-63,y=171,z=-63,dx=126,dy=33,dz=126,tag=!have_upgraded_sword_sharpnessI] add clear_iron_sword
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"绿锋利等级"=1}] ~~~ tag @a[scores={"分队"=3},x=-63,y=171,z=-63,dx=126,dy=33,dz=126,tag=!have_upgraded_sword_sharpnessI] add clear_diamond_sword
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"绿锋利等级"=1}] ~~~ tag @a[scores={"分队"=3,"剑等级"=1},x=-63,y=171,z=-63,dx=126,dy=33,dz=126,tag=!have_upgraded_sword_sharpnessI] add give_wooden_sword_sharpnessI
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"绿锋利等级"=1}] ~~~ tag @a[scores={"分队"=3,"剑等级"=2},x=-63,y=171,z=-63,dx=126,dy=33,dz=126,tag=!have_upgraded_sword_sharpnessI] add give_stone_sword_sharpnessI
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"绿锋利等级"=1}] ~~~ tag @a[scores={"分队"=3,"剑等级"=3},x=-63,y=171,z=-63,dx=126,dy=33,dz=126,tag=!have_upgraded_sword_sharpnessI] add give_iron_sword_sharpnessI
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"绿锋利等级"=1}] ~~~ tag @a[scores={"分队"=3,"剑等级"=4},x=-63,y=171,z=-63,dx=126,dy=33,dz=126,tag=!have_upgraded_sword_sharpnessI] add give_diamond_sword_sharpnessI
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"绿锋利等级"=1}] ~~~ tag @a[scores={"分队"=3}] add have_upgraded_sword_sharpnessI
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"绿锋利等级"=2}] ~~~ tag @a[scores={"分队"=3},x=-63,y=171,z=-63,dx=126,dy=33,dz=126,tag=!have_upgraded_sword_sharpnessII] add clear_wooden_sword_sharpnessI
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"绿锋利等级"=2}] ~~~ tag @a[scores={"分队"=3},x=-63,y=171,z=-63,dx=126,dy=33,dz=126,tag=!have_upgraded_sword_sharpnessII] add clear_stone_sword_sharpnessI
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"绿锋利等级"=2}] ~~~ tag @a[scores={"分队"=3},x=-63,y=171,z=-63,dx=126,dy=33,dz=126,tag=!have_upgraded_sword_sharpnessII] add clear_iron_sword_sharpnessI
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"绿锋利等级"=2}] ~~~ tag @a[scores={"分队"=3},x=-63,y=171,z=-63,dx=126,dy=33,dz=126,tag=!have_upgraded_sword_sharpnessII] add clear_diamond_sword_sharpnessI
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"绿锋利等级"=2}] ~~~ tag @a[scores={"分队"=3,"剑等级"=1},x=-63,y=171,z=-63,dx=126,dy=33,dz=126,tag=!have_upgraded_sword_sharpnessII] add give_wooden_sword_sharpnessII
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"绿锋利等级"=2}] ~~~ tag @a[scores={"分队"=3,"剑等级"=2},x=-63,y=171,z=-63,dx=126,dy=33,dz=126,tag=!have_upgraded_sword_sharpnessII] add give_stone_sword_sharpnessII
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"绿锋利等级"=2}] ~~~ tag @a[scores={"分队"=3,"剑等级"=3},x=-63,y=171,z=-63,dx=126,dy=33,dz=126,tag=!have_upgraded_sword_sharpnessII] add give_iron_sword_sharpnessII
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"绿锋利等级"=2}] ~~~ tag @a[scores={"分队"=3,"剑等级"=4},x=-63,y=171,z=-63,dx=126,dy=33,dz=126,tag=!have_upgraded_sword_sharpnessII] add give_diamond_sword_sharpnessII
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"绿锋利等级"=2}] ~~~ tag @a[scores={"分队"=3}] add have_upgraded_sword_sharpnessII
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"绿锋利等级"=3}] ~~~ tag @a[scores={"分队"=3},x=-63,y=171,z=-63,dx=126,dy=33,dz=126,tag=!have_upgraded_sword_sharpnessIII] add clear_wooden_sword_sharpnessII
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"绿锋利等级"=3}] ~~~ tag @a[scores={"分队"=3},x=-63,y=171,z=-63,dx=126,dy=33,dz=126,tag=!have_upgraded_sword_sharpnessIII] add clear_stone_sword_sharpnessII
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"绿锋利等级"=3}] ~~~ tag @a[scores={"分队"=3},x=-63,y=171,z=-63,dx=126,dy=33,dz=126,tag=!have_upgraded_sword_sharpnessIII] add clear_iron_sword_sharpnessII
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"绿锋利等级"=3}] ~~~ tag @a[scores={"分队"=3},x=-63,y=171,z=-63,dx=126,dy=33,dz=126,tag=!have_upgraded_sword_sharpnessIII] add clear_diamond_sword_sharpnessII
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"绿锋利等级"=3}] ~~~ tag @a[scores={"分队"=3,"剑等级"=1},x=-63,y=171,z=-63,dx=126,dy=33,dz=126,tag=!have_upgraded_sword_sharpnessIII] add give_wooden_sword_sharpnessIII  
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"绿锋利等级"=3}] ~~~ tag @a[scores={"分队"=3,"剑等级"=2},x=-63,y=171,z=-63,dx=126,dy=33,dz=126,tag=!have_upgraded_sword_sharpnessIII] add give_stone_sword_sharpnessIII   
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"绿锋利等级"=3}] ~~~ tag @a[scores={"分队"=3,"剑等级"=3},x=-63,y=171,z=-63,dx=126,dy=33,dz=126,tag=!have_upgraded_sword_sharpnessIII] add give_iron_sword_sharpnessIII    
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"绿锋利等级"=3}] ~~~ tag @a[scores={"分队"=3,"剑等级"=4},x=-63,y=171,z=-63,dx=126,dy=33,dz=126,tag=!have_upgraded_sword_sharpnessIII] add give_diamond_sword_sharpnessIII 
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"绿锋利等级"=3}] ~~~ tag @a[scores={"分队"=3}] add have_upgraded_sword_sharpnessIII