
execute @e[type=player,x=-200,y=200,z=-200,r=50,scores={分队=0,menu_page=3},tag=refresh_menu3] ~~~ clear @s
execute @e[type=player,x=-200,y=200,z=-200,r=50,scores={分队=0,menu_page=3},tag=refresh_menu3] ~~~ replaceitem entity @s slot.inventory 0 bedwars:menu_back 1 0 {"minecraft:item_lock":{"mode":"lock_in_inventory"}}
execute @e[type=armor_stand,name=main,tag=set.start.players.2] ~~~ execute @e[type=player,x=-200,y=200,z=-200,r=50,scores={分队=0,menu_page=3},tag=refresh_menu3] ~~~ replaceitem entity @s slot.inventory 14 bedwars:menu3_start_players_2 2 0 {"minecraft:item_lock":{"mode":"lock_in_slot"}}
execute @e[type=armor_stand,name=main,tag=set.start.players.3] ~~~ execute @e[type=player,x=-200,y=200,z=-200,r=50,scores={分队=0,menu_page=3},tag=refresh_menu3] ~~~ replaceitem entity @s slot.inventory 14 bedwars:menu3_start_players_3 3 0 {"minecraft:item_lock":{"mode":"lock_in_slot"}}
execute @e[type=armor_stand,name=main,tag=set.start.players.4] ~~~ execute @e[type=player,x=-200,y=200,z=-200,r=50,scores={分队=0,menu_page=3},tag=refresh_menu3] ~~~ replaceitem entity @s slot.inventory 14 bedwars:menu3_start_players_4 4 0 {"minecraft:item_lock":{"mode":"lock_in_slot"}}
execute @e[type=armor_stand,name=main,tag=set.start.players.5] ~~~ execute @e[type=player,x=-200,y=200,z=-200,r=50,scores={分队=0,menu_page=3},tag=refresh_menu3] ~~~ replaceitem entity @s slot.inventory 14 bedwars:menu3_start_players_5 5 0 {"minecraft:item_lock":{"mode":"lock_in_slot"}}
execute @e[type=armor_stand,name=main,tag=set.start.players.6] ~~~ execute @e[type=player,x=-200,y=200,z=-200,r=50,scores={分队=0,menu_page=3},tag=refresh_menu3] ~~~ replaceitem entity @s slot.inventory 14 bedwars:menu3_start_players_6 6 0 {"minecraft:item_lock":{"mode":"lock_in_slot"}}
execute @e[type=armor_stand,name=main,tag=set.start.players.7] ~~~ execute @e[type=player,x=-200,y=200,z=-200,r=50,scores={分队=0,menu_page=3},tag=refresh_menu3] ~~~ replaceitem entity @s slot.inventory 14 bedwars:menu3_start_players_7 7 0 {"minecraft:item_lock":{"mode":"lock_in_slot"}}
execute @e[type=armor_stand,name=main,tag=set.start.players.8] ~~~ execute @e[type=player,x=-200,y=200,z=-200,r=50,scores={分队=0,menu_page=3},tag=refresh_menu3] ~~~ replaceitem entity @s slot.inventory 14 bedwars:menu3_start_players_8 8 0 {"minecraft:item_lock":{"mode":"lock_in_slot"}}
execute @e[type=armor_stand,name=main,tag=!set.start.players.2] ~~~ execute @e[type=player,x=-200,y=200,z=-200,r=50,scores={分队=0,menu_page=3},tag=refresh_menu3] ~~~ replaceitem entity @s slot.inventory 13 bedwars:menu3_remove_start_players_required 1 0 {"minecraft:item_lock":{"mode":"lock_in_inventory"}}
execute @e[type=armor_stand,name=main,tag=set.start.players.2] ~~~ execute @e[type=player,x=-200,y=200,z=-200,r=50,scores={分队=0,menu_page=3},tag=refresh_menu3] ~~~ replaceitem entity @s slot.inventory 13 bedwars:menu3_start_players_reachmin 1 0 {"minecraft:item_lock":{"mode":"lock_in_slot"}}
execute @e[type=armor_stand,name=main,tag=!set.start.players.8] ~~~ execute @e[type=player,x=-200,y=200,z=-200,r=50,scores={分队=0,menu_page=3},tag=refresh_menu3] ~~~ replaceitem entity @s slot.inventory 15 bedwars:menu3_add_start_players_required 1 0 {"minecraft:item_lock":{"mode":"lock_in_inventory"}}
execute @e[type=armor_stand,name=main,tag=set.start.players.8] ~~~ execute @e[type=player,x=-200,y=200,z=-200,r=50,scores={分队=0,menu_page=3},tag=refresh_menu3] ~~~ replaceitem entity @s slot.inventory 15 bedwars:menu3_start_players_reachmax 1 0 {"minecraft:item_lock":{"mode":"lock_in_slot"}}
execute @e[type=player,x=-200,y=200,z=-200,r=50,scores={分队=0},tag=refresh_menu3] ~~~ tag @s remove refresh_menu3
