# 升级到铁护甲
execute @e[type=armor_stand,scores={gameSTART=1,"红保护等级"=0},name=main] ~~~ execute @e[type=player,tag=up_armor,scores={"防具等级"=2,"分队"=1}] ~~~ replaceitem entity @s slot.armor.legs 0 iron_leggings 1 0 {"minecraft:item_lock":{"mode":"lock_in_slot"},"minecraft:keep_on_death":{}}
execute @e[type=armor_stand,scores={gameSTART=1,"红保护等级"=0},name=main] ~~~ execute @e[type=player,tag=up_armor,scores={"防具等级"=2,"分队"=1}] ~~~ replaceitem entity @s slot.armor.feet 0 iron_boots 1 0 {"minecraft:item_lock":{"mode":"lock_in_slot"},"minecraft:keep_on_death":{}}
execute @e[type=armor_stand,scores={gameSTART=1,"红保护等级"=1},name=main] ~~~ execute @e[type=player,tag=up_armor,scores={"防具等级"=2,"分队"=1}] ~~~ replaceitem entity @s slot.armor.legs 0 bedwars:iron_leggings_protectionI 1 0 {"minecraft:item_lock":{"mode":"lock_in_slot"},"minecraft:keep_on_death":{}}
execute @e[type=armor_stand,scores={gameSTART=1,"红保护等级"=1},name=main] ~~~ execute @e[type=player,tag=up_armor,scores={"防具等级"=2,"分队"=1}] ~~~ replaceitem entity @s slot.armor.feet 0 bedwars:iron_boots_protectionI 1 0 {"minecraft:item_lock":{"mode":"lock_in_slot"},"minecraft:keep_on_death":{}}
execute @e[type=armor_stand,scores={gameSTART=1,"红保护等级"=2},name=main] ~~~ execute @e[type=player,tag=up_armor,scores={"防具等级"=2,"分队"=1}] ~~~ replaceitem entity @s slot.armor.legs 0 bedwars:iron_leggings_protectionII 1 0 {"minecraft:item_lock":{"mode":"lock_in_slot"},"minecraft:keep_on_death":{}}
execute @e[type=armor_stand,scores={gameSTART=1,"红保护等级"=2},name=main] ~~~ execute @e[type=player,tag=up_armor,scores={"防具等级"=2,"分队"=1}] ~~~ replaceitem entity @s slot.armor.feet 0 bedwars:iron_boots_protectionII 1 0 {"minecraft:item_lock":{"mode":"lock_in_slot"},"minecraft:keep_on_death":{}}
execute @e[type=armor_stand,scores={gameSTART=1,"红保护等级"=3},name=main] ~~~ execute @e[type=player,tag=up_armor,scores={"防具等级"=2,"分队"=1}] ~~~ replaceitem entity @s slot.armor.legs 0 bedwars:iron_leggings_protectionIII 1 0 {"minecraft:item_lock":{"mode":"lock_in_slot"},"minecraft:keep_on_death":{}}
execute @e[type=armor_stand,scores={gameSTART=1,"红保护等级"=3},name=main] ~~~ execute @e[type=player,tag=up_armor,scores={"防具等级"=2,"分队"=1}] ~~~ replaceitem entity @s slot.armor.feet 0 bedwars:iron_boots_protectionIII 1 0 {"minecraft:item_lock":{"mode":"lock_in_slot"},"minecraft:keep_on_death":{}}
execute @e[type=armor_stand,scores={gameSTART=1,"蓝保护等级"=0},name=main] ~~~ execute @e[type=player,tag=up_armor,scores={"防具等级"=2,"分队"=2}] ~~~ replaceitem entity @s slot.armor.legs 0 iron_leggings 1 0 {"minecraft:item_lock":{"mode":"lock_in_slot"},"minecraft:keep_on_death":{}}
execute @e[type=armor_stand,scores={gameSTART=1,"蓝保护等级"=0},name=main] ~~~ execute @e[type=player,tag=up_armor,scores={"防具等级"=2,"分队"=2}] ~~~ replaceitem entity @s slot.armor.feet 0 iron_boots 1 0 {"minecraft:item_lock":{"mode":"lock_in_slot"},"minecraft:keep_on_death":{}}
execute @e[type=armor_stand,scores={gameSTART=1,"蓝保护等级"=1},name=main] ~~~ execute @e[type=player,tag=up_armor,scores={"防具等级"=2,"分队"=2}] ~~~ replaceitem entity @s slot.armor.legs 0 bedwars:iron_leggings_protectionI 1 0 {"minecraft:item_lock":{"mode":"lock_in_slot"},"minecraft:keep_on_death":{}}
execute @e[type=armor_stand,scores={gameSTART=1,"蓝保护等级"=1},name=main] ~~~ execute @e[type=player,tag=up_armor,scores={"防具等级"=2,"分队"=2}] ~~~ replaceitem entity @s slot.armor.feet 0 bedwars:iron_boots_protectionI 1 0 {"minecraft:item_lock":{"mode":"lock_in_slot"},"minecraft:keep_on_death":{}}
execute @e[type=armor_stand,scores={gameSTART=1,"蓝保护等级"=2},name=main] ~~~ execute @e[type=player,tag=up_armor,scores={"防具等级"=2,"分队"=2}] ~~~ replaceitem entity @s slot.armor.legs 0 bedwars:iron_leggings_protectionII 1 0 {"minecraft:item_lock":{"mode":"lock_in_slot"},"minecraft:keep_on_death":{}}
execute @e[type=armor_stand,scores={gameSTART=1,"蓝保护等级"=2},name=main] ~~~ execute @e[type=player,tag=up_armor,scores={"防具等级"=2,"分队"=2}] ~~~ replaceitem entity @s slot.armor.feet 0 bedwars:iron_boots_protectionII 1 0 {"minecraft:item_lock":{"mode":"lock_in_slot"},"minecraft:keep_on_death":{}}
execute @e[type=armor_stand,scores={gameSTART=1,"蓝保护等级"=3},name=main] ~~~ execute @e[type=player,tag=up_armor,scores={"防具等级"=2,"分队"=2}] ~~~ replaceitem entity @s slot.armor.legs 0 bedwars:iron_leggings_protectionIII 1 0 {"minecraft:item_lock":{"mode":"lock_in_slot"},"minecraft:keep_on_death":{}}
execute @e[type=armor_stand,scores={gameSTART=1,"蓝保护等级"=3},name=main] ~~~ execute @e[type=player,tag=up_armor,scores={"防具等级"=2,"分队"=2}] ~~~ replaceitem entity @s slot.armor.feet 0 bedwars:iron_boots_protectionIII 1 0 {"minecraft:item_lock":{"mode":"lock_in_slot"},"minecraft:keep_on_death":{}}
execute @e[type=armor_stand,scores={gameSTART=1},name=main] ~~~ execute @e[type=player,tag=up_armor,scores={"防具等级"=2}] ~~~ scoreboard players set @s "防具等级" 3
execute @e[type=armor_stand,scores={gameSTART=1},name=main] ~~~ execute @e[type=player,tag=up_armor,scores={"防具等级"=3}] ~~~ tellraw @s { "rawtext" : [ { "text" : "§f§lShop >> §7§lYour armor level is now 3 §f(iron)" } ] }
execute @e[type=armor_stand,scores={gameSTART=1},name=main] ~~~ execute @e[type=player,tag=up_armor,scores={"防具等级"=3}] ~~~ tag @s remove up_armor
