tag @a[scores={"分队"=1}] remove team2
tag @a[scores={"分队"=1}] remove team3
tag @a[scores={"分队"=1}] remove team4
tag @a[scores={"分队"=2}] remove team1
tag @a[scores={"分队"=2}] remove team3
tag @a[scores={"分队"=2}] remove team4
tag @a[scores={"分队"=3}] remove team1
tag @a[scores={"分队"=3}] remove team2
tag @a[scores={"分队"=3}] remove team4
tag @a[scores={"分队"=4}] remove team1
tag @a[scores={"分队"=4}] remove team2
tag @a[scores={"分队"=4}] remove team3
tag @a[scores={"分队"=1}] add team1
tag @a[scores={"分队"=2}] add team2
tag @a[scores={"分队"=3}] add team3
tag @a[scores={"分队"=4}] add team4