# 升级到石剑
execute @e[type=armor_stand,scores={gameSTART=1,"红锋利等级"=0},name=main] ~~~ execute @e[type=player,tag=up_sword,scores={"剑等级"=1,"分队"=1}] ~~~ clear @s bedwars:wooden_sword
execute @e[type=armor_stand,scores={gameSTART=1,"红锋利等级"=0},name=main] ~~~ execute @e[type=player,tag=up_sword,scores={"剑等级"=1,"分队"=1}] ~~~ give @s bedwars:stone_sword 1 0 {"minecraft:item_lock":{"mode":"lock_in_inventory"},"minecraft:keep_on_death":{}}
execute @e[type=armor_stand,scores={gameSTART=1,"红锋利等级"=1},name=main] ~~~ execute @e[type=player,tag=up_sword,scores={"剑等级"=1,"分队"=1}] ~~~ clear @s bedwars:wooden_sword_sharpnessI
execute @e[type=armor_stand,scores={gameSTART=1,"红锋利等级"=1},name=main] ~~~ execute @e[type=player,tag=up_sword,scores={"剑等级"=1,"分队"=1}] ~~~ give @s bedwars:stone_sword_sharpnessI 1 0 {"minecraft:item_lock":{"mode":"lock_in_inventory"},"minecraft:keep_on_death":{}}
execute @e[type=armor_stand,scores={gameSTART=1,"红锋利等级"=2},name=main] ~~~ execute @e[type=player,tag=up_sword,scores={"剑等级"=1,"分队"=1}] ~~~ clear @s bedwars:wooden_sword_sharpnessII
execute @e[type=armor_stand,scores={gameSTART=1,"红锋利等级"=2},name=main] ~~~ execute @e[type=player,tag=up_sword,scores={"剑等级"=1,"分队"=1}] ~~~ give @s bedwars:stone_sword_sharpnessII 1 0 {"minecraft:item_lock":{"mode":"lock_in_inventory"},"minecraft:keep_on_death":{}}
execute @e[type=armor_stand,scores={gameSTART=1,"红锋利等级"=3},name=main] ~~~ execute @e[type=player,tag=up_sword,scores={"剑等级"=1,"分队"=1}] ~~~ clear @s bedwars:wooden_sword_sharpnessIII
execute @e[type=armor_stand,scores={gameSTART=1,"红锋利等级"=3},name=main] ~~~ execute @e[type=player,tag=up_sword,scores={"剑等级"=1,"分队"=1}] ~~~ give @s bedwars:stone_sword_sharpnessIII 1 0 {"minecraft:item_lock":{"mode":"lock_in_inventory"},"minecraft:keep_on_death":{}}
execute @e[type=armor_stand,scores={gameSTART=1,"蓝锋利等级"=0},name=main] ~~~ execute @e[type=player,tag=up_sword,scores={"剑等级"=1,"分队"=2}] ~~~ clear @s bedwars:wooden_sword
execute @e[type=armor_stand,scores={gameSTART=1,"蓝锋利等级"=0},name=main] ~~~ execute @e[type=player,tag=up_sword,scores={"剑等级"=1,"分队"=2}] ~~~ give @s bedwars:stone_sword 1 0 {"minecraft:item_lock":{"mode":"lock_in_inventory"},"minecraft:keep_on_death":{}}
execute @e[type=armor_stand,scores={gameSTART=1,"蓝锋利等级"=1},name=main] ~~~ execute @e[type=player,tag=up_sword,scores={"剑等级"=1,"分队"=2}] ~~~ clear @s bedwars:wooden_sword_sharpnessI
execute @e[type=armor_stand,scores={gameSTART=1,"蓝锋利等级"=1},name=main] ~~~ execute @e[type=player,tag=up_sword,scores={"剑等级"=1,"分队"=2}] ~~~ give @s bedwars:stone_sword_sharpnessI 1 0 {"minecraft:item_lock":{"mode":"lock_in_inventory"},"minecraft:keep_on_death":{}}
execute @e[type=armor_stand,scores={gameSTART=1,"蓝锋利等级"=2},name=main] ~~~ execute @e[type=player,tag=up_sword,scores={"剑等级"=1,"分队"=2}] ~~~ clear @s bedwars:wooden_sword_sharpnessII
execute @e[type=armor_stand,scores={gameSTART=1,"蓝锋利等级"=2},name=main] ~~~ execute @e[type=player,tag=up_sword,scores={"剑等级"=1,"分队"=2}] ~~~ give @s bedwars:stone_sword_sharpnessII 1 0 {"minecraft:item_lock":{"mode":"lock_in_inventory"},"minecraft:keep_on_death":{}}
execute @e[type=armor_stand,scores={gameSTART=1,"蓝锋利等级"=3},name=main] ~~~ execute @e[type=player,tag=up_sword,scores={"剑等级"=1,"分队"=2}] ~~~ clear @s bedwars:wooden_sword_sharpnessIII
execute @e[type=armor_stand,scores={gameSTART=1,"蓝锋利等级"=3},name=main] ~~~ execute @e[type=player,tag=up_sword,scores={"剑等级"=1,"分队"=2}] ~~~ give @s bedwars:stone_sword_sharpnessIII 1 0 {"minecraft:item_lock":{"mode":"lock_in_inventory"},"minecraft:keep_on_death":{}}
execute @e[type=armor_stand,scores={gameSTART=1,"黄锋利等级"=0},name=main] ~~~ execute @e[type=player,tag=up_sword,scores={"剑等级"=1,"分队"=3}] ~~~ clear @s bedwars:wooden_sword
execute @e[type=armor_stand,scores={gameSTART=1,"黄锋利等级"=0},name=main] ~~~ execute @e[type=player,tag=up_sword,scores={"剑等级"=1,"分队"=3}] ~~~ give @s bedwars:stone_sword 1 0 {"minecraft:item_lock":{"mode":"lock_in_inventory"},"minecraft:keep_on_death":{}}
execute @e[type=armor_stand,scores={gameSTART=1,"黄锋利等级"=1},name=main] ~~~ execute @e[type=player,tag=up_sword,scores={"剑等级"=1,"分队"=3}] ~~~ clear @s bedwars:wooden_sword_sharpnessI
execute @e[type=armor_stand,scores={gameSTART=1,"黄锋利等级"=1},name=main] ~~~ execute @e[type=player,tag=up_sword,scores={"剑等级"=1,"分队"=3}] ~~~ give @s bedwars:stone_sword_sharpnessI 1 0 {"minecraft:item_lock":{"mode":"lock_in_inventory"},"minecraft:keep_on_death":{}}
execute @e[type=armor_stand,scores={gameSTART=1,"黄锋利等级"=2},name=main] ~~~ execute @e[type=player,tag=up_sword,scores={"剑等级"=1,"分队"=3}] ~~~ clear @s bedwars:wooden_sword_sharpnessII
execute @e[type=armor_stand,scores={gameSTART=1,"黄锋利等级"=2},name=main] ~~~ execute @e[type=player,tag=up_sword,scores={"剑等级"=1,"分队"=3}] ~~~ give @s bedwars:stone_sword_sharpnessII 1 0 {"minecraft:item_lock":{"mode":"lock_in_inventory"},"minecraft:keep_on_death":{}}
execute @e[type=armor_stand,scores={gameSTART=1,"黄锋利等级"=3},name=main] ~~~ execute @e[type=player,tag=up_sword,scores={"剑等级"=1,"分队"=3}] ~~~ clear @s bedwars:wooden_sword_sharpnessIII
execute @e[type=armor_stand,scores={gameSTART=1,"黄锋利等级"=3},name=main] ~~~ execute @e[type=player,tag=up_sword,scores={"剑等级"=1,"分队"=3}] ~~~ give @s bedwars:stone_sword_sharpnessIII 1 0 {"minecraft:item_lock":{"mode":"lock_in_inventory"},"minecraft:keep_on_death":{}}
execute @e[type=armor_stand,scores={gameSTART=1,"绿锋利等级"=0},name=main] ~~~ execute @e[type=player,tag=up_sword,scores={"剑等级"=1,"分队"=4}] ~~~ clear @s bedwars:wooden_sword
execute @e[type=armor_stand,scores={gameSTART=1,"绿锋利等级"=0},name=main] ~~~ execute @e[type=player,tag=up_sword,scores={"剑等级"=1,"分队"=4}] ~~~ give @s bedwars:stone_sword 1 0 {"minecraft:item_lock":{"mode":"lock_in_inventory"},"minecraft:keep_on_death":{}}
execute @e[type=armor_stand,scores={gameSTART=1,"绿锋利等级"=1},name=main] ~~~ execute @e[type=player,tag=up_sword,scores={"剑等级"=1,"分队"=4}] ~~~ clear @s bedwars:wooden_sword_sharpnessI
execute @e[type=armor_stand,scores={gameSTART=1,"绿锋利等级"=1},name=main] ~~~ execute @e[type=player,tag=up_sword,scores={"剑等级"=1,"分队"=4}] ~~~ give @s bedwars:stone_sword_sharpnessI 1 0 {"minecraft:item_lock":{"mode":"lock_in_inventory"},"minecraft:keep_on_death":{}}
execute @e[type=armor_stand,scores={gameSTART=1,"绿锋利等级"=2},name=main] ~~~ execute @e[type=player,tag=up_sword,scores={"剑等级"=1,"分队"=4}] ~~~ clear @s bedwars:wooden_sword_sharpnessII
execute @e[type=armor_stand,scores={gameSTART=1,"绿锋利等级"=2},name=main] ~~~ execute @e[type=player,tag=up_sword,scores={"剑等级"=1,"分队"=4}] ~~~ give @s bedwars:stone_sword_sharpnessII 1 0 {"minecraft:item_lock":{"mode":"lock_in_inventory"},"minecraft:keep_on_death":{}}
execute @e[type=armor_stand,scores={gameSTART=1,"绿锋利等级"=3},name=main] ~~~ execute @e[type=player,tag=up_sword,scores={"剑等级"=1,"分队"=4}] ~~~ clear @s bedwars:wooden_sword_sharpnessIII
execute @e[type=armor_stand,scores={gameSTART=1,"绿锋利等级"=3},name=main] ~~~ execute @e[type=player,tag=up_sword,scores={"剑等级"=1,"分队"=4}] ~~~ give @s bedwars:stone_sword_sharpnessIII 1 0 {"minecraft:item_lock":{"mode":"lock_in_inventory"},"minecraft:keep_on_death":{}}
execute @e[type=armor_stand,scores={gameSTART=1},name=main] ~~~ execute @e[type=player,tag=up_sword,scores={"剑等级"=1}] ~~~ scoreboard players set @s "剑等级" 2
execute @e[type=armor_stand,scores={gameSTART=1},name=main] ~~~ execute @e[type=player,tag=up_sword,scores={"剑等级"=2}] ~~~ tellraw @s { "rawtext" : [{"translate":"text.tellraw.ingameinfo.purchase_now_stone_sword"} ] }
execute @e[type=armor_stand,scores={gameSTART=1},name=main] ~~~ execute @e[type=player,tag=up_sword,scores={"剑等级"=2}] ~~~ tag @s remove up_sword