setblock ~~~1 bedwars:map_smooth_stone_slab_block 
setblock ~~~2 bedwars:map_iron_block 
setblock ~~~3 bedwars:menu999_purchase_confirm 
setblock ~~~4 bedwars:menu999_purchase_cancel 
setblock ~~~5 bedwars:lobby_button_select_map_next_block 
setblock ~~~6 bedwars:lobby_button_select_map_last_block 
setblock ~~~7 bedwars:lobby_button_select_mode_next_block 
setblock ~~~8 bedwars:lobby_button_select_mode_last_block 
setblock ~~~9 bedwars:purchase_red_wool_block 
setblock ~~~10 bedwars:purchase_blue_wool_block 
setblock ~~~11 bedwars:purchase_yellow_wool_block 
setblock ~~~12 bedwars:purchase_green_wool_block 
setblock ~~~13 bedwars:purchase_endstone_block 
setblock ~~~14 bedwars:purchase_planks_block 
setblock ~~~15 bedwars:purchase_red_stained_glass_block 
setblock ~~~16 bedwars:purchase_blue_stained_glass_block 
setblock ~~~17 bedwars:purchase_yellow_stained_glass_block 
setblock ~~~18 bedwars:purchase_green_stained_glass_block 
setblock ~~~19 bedwars:purchase_upgrade_sword_block 
setblock ~~~20 bedwars:purchase_upgrade_pickaxe_block 
setblock ~~~21 bedwars:purchase_upgrade_axe_block 
setblock ~~~22 bedwars:purchase_upgrade_armor_block 
setblock ~~~23 bedwars:purchase_upgrade_bow_block 
setblock ~~~24 bedwars:purchase_arrow_block 
setblock ~~~25 bedwars:get_trap_info_block 
setblock ~~~26 bedwars:get_upgrade_and_trap_help_block 
setblock ~~~27 bedwars:purchase_team_miner_fatigue_trap_block 
setblock ~~~28 bedwars:purchase_team_alarm_trap_block 
setblock ~~~29 bedwars:purchase_team_its_a_trap_block 
setblock ~~~30 bedwars:purchase_team_counter-offensive_block 
setblock ~~~31 bedwars:purchase_upgrade_team_maniac_miner_block 
setblock ~~~32 bedwars:purchase_upgrade_team_sharpness_block 
setblock ~~~33 bedwars:purchase_upgrade_team_protection_block 
setblock ~~~34 bedwars:purchase_upgrade_team_forge_block 
setblock ~~~35 bedwars:purchase_golden_apple_block 
setblock ~~~36 bedwars:purchase_fireball_block 
setblock ~~~37 bedwars:purchase_tnt_block 
setblock ~~~38 bedwars:purchase_speed_potion_block 
setblock ~~~39 bedwars:purchase_jump_boost_potion_block 
setblock ~~~40 bedwars:purchase_invisibility_potion_block 
setblock ~~~41 bedwars:purchase_xp_bottle_block 
setblock ~~~42 bedwars:purchase_popup_tower_block 
setblock ~~~43 bedwars:purchase_bridge_egg_block 
setblock ~~~44 bedwars:purchase_silverfish_block 
setblock ~~~45 bedwars:tnt2_block 
setblock ~~~46 bedwars:player_red_stained_glass 
setblock ~~~47 bedwars:player_blue_stained_glass 
setblock ~~~48 bedwars:player_yellow_stained_glass 
setblock ~~~49 bedwars:player_green_stained_glass 
setblock ~~~50 bedwars:log_spruce2 
setblock ~~~51 bedwars:map_diamond_block 
setblock ~~~52 bedwars:map_emerald_block 
setblock ~~~53 bedwars:map_red_wool_block 
setblock ~~~54 bedwars:map_light_blue_wool_block 
setblock ~~~55 bedwars:map_yellow_wool_block 
setblock ~~~56 bedwars:map_green_wool_block 
setblock ~~~57 bedwars:map_white_stained_glass 
setblock ~~~58 bedwars:map_sand_block 
setblock ~~~59 bedwars:player_red_wool 
setblock ~~~60 bedwars:player_blue_wool 
setblock ~~~61 bedwars:player_yellow_wool 
setblock ~~~62 bedwars:player_green_wool 
setblock ~~~63 bedwars:player_planks 
setblock ~~~64 bedwars:player_endstone 
setblock ~~~65 bedwars:player_obsidian 
setblock ~~~66 bedwars:red_popup_tower 
setblock ~~~67 bedwars:blue_popup_tower 
setblock ~~~68 bedwars:yellow_popup_tower 
setblock ~~~69 bedwars:green_popup_tower 
setblock ~~~70 bedwars:red_wool_particle 
setblock ~~~71 bedwars:blue_wool_particle 
setblock ~~~72 bedwars:yellow_wool_particle 
setblock ~~~73 bedwars:green_wool_particle 
setblock ~~~74 bedwars:map_prismarine_block 
setblock ~~~75 bedwars:map_normal_concrete_block 
setblock ~~~76 bedwars:map_blue_concrete_block 
setblock ~~~77 bedwars:map_blue_concrete2_block 
setblock ~~~78 bedwars:map_blue_stained_glass_block 
setblock ~~~79 bedwars:map_bone_cross1_block 
setblock ~~~80 bedwars:map_bone_cross2_block 
setblock ~~~81 bedwars:map_bone_vertical_block 
setblock ~~~82 bedwars:map_cobbled_deepslate_block 
setblock ~~~83 bedwars:map_crying_obsidian_block 
setblock ~~~84 bedwars:map_cyan_concrete_block 
setblock ~~~85 bedwars:map_cyan_concrete2_block 
setblock ~~~86 bedwars:map_dark_prismarine_block 
setblock ~~~87 bedwars:map_dirt_block 
setblock ~~~88 bedwars:map_grass_block 
setblock ~~~89 bedwars:map_dark_oak_log_block 
setblock ~~~90 bedwars:map_jungle_log_block 
setblock ~~~91 bedwars:map_light_blue_concrete_block 
setblock ~~~92 bedwars:map_light_blue_concrete2_block 
setblock ~~~93 bedwars:map_light_gray_concrete_block 
setblock ~~~94 bedwars:map_gray_concrete_block 
setblock ~~~95 bedwars:map_light_blue_stained_glass_block 
setblock ~~~96 bedwars:map_obsidian_block 
setblock ~~~97 bedwars:map_prismarine_brick_block 
setblock ~~~98 bedwars:map_red_concrete_block 
setblock ~~~99 bedwars:map_red_sandstone_block 
setblock ~~~100 bedwars:map_sandstone_block 
setblock ~~~101 bedwars:map_sea_lantern_block 
setblock ~~~102 bedwars:map_stone_block 
setblock ~~~103 bedwars:map_white_concrete_block 
setblock ~~~104 bedwars:map_white_wool_block 
setblock ~~~105 bedwars:map_yellow_concrete_block 
setblock ~~~106 bedwars:map_green_concrete_block 
setblock ~~~107 bedwars:red_bed_foot 
setblock ~~~108 bedwars:red_bed_head 
setblock ~~~109 bedwars:blue_bed_foot 
setblock ~~~110 bedwars:blue_bed_head 
setblock ~~~111 bedwars:yellow_bed_foot 
setblock ~~~112 bedwars:yellow_bed_head 
setblock ~~~113 bedwars:green_bed_foot 
setblock ~~~114 bedwars:green_bed_head 
setblock ~~~115 bedwars:map_barrel_block 
setblock ~~~116 bedwars:map_bedrock_block 
setblock ~~~117 bedwars:map_black_concrete_block 
setblock ~~~118 bedwars:map_block_of_quartz_block 
setblock ~~~119 bedwars:map_brick_block 
setblock ~~~120 bedwars:map_chiseled_sandstone_block 
setblock ~~~121 bedwars:map_coarse_dirt_block 
setblock ~~~122 bedwars:map_cobblestone_block 
setblock ~~~123 bedwars:map_copper_ore_block 
setblock ~~~124 bedwars:map_cracked_deepslate_tiles_block 
setblock ~~~125 bedwars:map_cracked_stone_bricks_block 
setblock ~~~126 bedwars:map_cyan_stained_glass_block 
setblock ~~~127 bedwars:map_dark_oak_planks_block 
setblock ~~~128 bedwars:map_deepslate_diamond_ore_block 
setblock ~~~129 bedwars:map_deepslate_gold_ore_block 
setblock ~~~130 bedwars:map_deepslate_iron_ore_block 
setblock ~~~131 bedwars:map_dried_kelp_block 
setblock ~~~132 bedwars:map_gravel_block 
setblock ~~~133 bedwars:map_hay_bale_block 
setblock ~~~134 bedwars:map_infested_deepslate_block 
setblock ~~~135 bedwars:map_jungle_leaves_block 
setblock ~~~136 bedwars:map_lime_concrete_block 
setblock ~~~137 bedwars:map_moss_block 
setblock ~~~138 bedwars:map_mossy_cobblestone_block 
setblock ~~~139 bedwars:map_oak_wood_block 
setblock ~~~140 bedwars:map_pillar_quartz_block 
setblock ~~~141 bedwars:map_red_sand_block 
setblock ~~~142 bedwars:map_smooth_red_sandstone_block 
setblock ~~~143 bedwars:map_smooth_sandstone_block 
setblock ~~~144 bedwars:map_smooth_stone_block 
setblock ~~~145 bedwars:map_spruce_planks_block 
setblock ~~~146 bedwars:map_stone_bricks_block 
setblock ~~~147 bedwars:map_dark_oak_leaves_block 
setblock ~~~148 bedwars:purchase_magic_milk_block 