execute @s[type=armor_stand,scores={"开始倒计时"=20},tag=reset_OK] ~~~ scoreboard players set "§aStart in 20s" "等待显示" -5
execute @s[type=armor_stand,scores={"开始倒计时"=19},tag=reset_OK] ~~~ scoreboard players set "§aStart in 19s" "等待显示" -5
execute @s[type=armor_stand,scores={"开始倒计时"=18},tag=reset_OK] ~~~ scoreboard players set "§aStart in 18s" "等待显示" -5
execute @s[type=armor_stand,scores={"开始倒计时"=17},tag=reset_OK] ~~~ scoreboard players set "§aStart in 17s" "等待显示" -5
execute @s[type=armor_stand,scores={"开始倒计时"=16},tag=reset_OK] ~~~ scoreboard players set "§aStart in 16s" "等待显示" -5
execute @s[type=armor_stand,scores={"开始倒计时"=15},tag=reset_OK] ~~~ scoreboard players set "§aStart in 15s" "等待显示" -5
execute @s[type=armor_stand,scores={"开始倒计时"=14},tag=reset_OK] ~~~ scoreboard players set "§aStart in 14s" "等待显示" -5
execute @s[type=armor_stand,scores={"开始倒计时"=13},tag=reset_OK] ~~~ scoreboard players set "§aStart in 13s" "等待显示" -5
execute @s[type=armor_stand,scores={"开始倒计时"=12},tag=reset_OK] ~~~ scoreboard players set "§aStart in 12s" "等待显示" -5
execute @s[type=armor_stand,scores={"开始倒计时"=11},tag=reset_OK] ~~~ scoreboard players set "§aStart in 11s" "等待显示" -5
execute @s[type=armor_stand,scores={"开始倒计时"=10},tag=reset_OK] ~~~ scoreboard players set "§aStart in 10s" "等待显示" -5
execute @s[type=armor_stand,scores={"开始倒计时"=9},tag=reset_OK] ~~~ scoreboard players set "§aStart in 9s" "等待显示" -5
execute @s[type=armor_stand,scores={"开始倒计时"=8},tag=reset_OK] ~~~ scoreboard players set "§aStart in 8s" "等待显示" -5
execute @s[type=armor_stand,scores={"开始倒计时"=7},tag=reset_OK] ~~~ scoreboard players set "§aStart in 7s" "等待显示" -5
execute @s[type=armor_stand,scores={"开始倒计时"=6},tag=reset_OK] ~~~ scoreboard players set "§aStart in 6s" "等待显示" -5
execute @s[type=armor_stand,scores={"开始倒计时"=5},tag=reset_OK] ~~~ scoreboard players set "§aStart in 5s" "等待显示" -5
execute @s[type=armor_stand,scores={"开始倒计时"=4},tag=reset_OK] ~~~ scoreboard players set "§aStart in 4s" "等待显示" -5
execute @s[type=armor_stand,scores={"开始倒计时"=3},tag=reset_OK] ~~~ scoreboard players set "§aStart in 3s" "等待显示" -5
execute @s[type=armor_stand,scores={"开始倒计时"=2},tag=reset_OK] ~~~ scoreboard players set "§aStart in 2s" "等待显示" -5
execute @s[type=armor_stand,scores={"开始倒计时"=1},tag=reset_OK] ~~~ scoreboard players set "§aStart in 1s" "等待显示" -5