execute @e[type=armor_stand,name=main,scores={gameSTART=1,"红保护等级"=1}] ~~~ replaceitem entity @a[scores={"分队"=1},x=-63,y=171,z=-63,dx=126,dy=33,dz=126] slot.armor.head 0 bedwars:red_team_helmet_protectionI
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"红保护等级"=1}] ~~~ replaceitem entity @a[scores={"分队"=1},x=-63,y=171,z=-63,dx=126,dy=33,dz=126] slot.armor.chest 0 bedwars:red_team_chestplate_protectionI
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"红保护等级"=1}] ~~~ replaceitem entity @a[scores={"分队"=1,"防具等级"=1},x=-63,y=171,z=-63,dx=126,dy=33,dz=126] slot.armor.legs 0 bedwars:red_team_leggings_protectionI  
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"红保护等级"=1}] ~~~ replaceitem entity @a[scores={"分队"=1,"防具等级"=1},x=-63,y=171,z=-63,dx=126,dy=33,dz=126] slot.armor.feet 0 bedwars:red_team_boots_protectionI     
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"红保护等级"=1}] ~~~ replaceitem entity @a[scores={"分队"=1,"防具等级"=2},x=-63,y=171,z=-63,dx=126,dy=33,dz=126] slot.armor.legs 0 bedwars:chainmail_leggings_protectionI
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"红保护等级"=1}] ~~~ replaceitem entity @a[scores={"分队"=1,"防具等级"=2},x=-63,y=171,z=-63,dx=126,dy=33,dz=126] slot.armor.feet 0 bedwars:chainmail_boots_protectionI
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"红保护等级"=1}] ~~~ replaceitem entity @a[scores={"分队"=1,"防具等级"=3},x=-63,y=171,z=-63,dx=126,dy=33,dz=126] slot.armor.legs 0 bedwars:iron_leggings_protectionI
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"红保护等级"=1}] ~~~ replaceitem entity @a[scores={"分队"=1,"防具等级"=3},x=-63,y=171,z=-63,dx=126,dy=33,dz=126] slot.armor.feet 0 bedwars:iron_boots_protectionI
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"红保护等级"=1}] ~~~ replaceitem entity @a[scores={"分队"=1,"防具等级"=4},x=-63,y=171,z=-63,dx=126,dy=33,dz=126] slot.armor.legs 0 bedwars:diamond_leggings_protectionI
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"红保护等级"=1}] ~~~ replaceitem entity @a[scores={"分队"=1,"防具等级"=4},x=-63,y=171,z=-63,dx=126,dy=33,dz=126] slot.armor.feet 0 bedwars:diamond_boots_protectionI
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"红保护等级"=2}] ~~~ replaceitem entity @a[scores={"分队"=1},x=-63,y=171,z=-63,dx=126,dy=33,dz=126] slot.armor.head 0 bedwars:red_team_helmet_protectionII
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"红保护等级"=2}] ~~~ replaceitem entity @a[scores={"分队"=1},x=-63,y=171,z=-63,dx=126,dy=33,dz=126] slot.armor.chest 0 bedwars:red_team_chestplate_protectionII
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"红保护等级"=2}] ~~~ replaceitem entity @a[scores={"分队"=1,"防具等级"=1},x=-63,y=171,z=-63,dx=126,dy=33,dz=126] slot.armor.legs 0 bedwars:red_team_leggings_protectionII
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"红保护等级"=2}] ~~~ replaceitem entity @a[scores={"分队"=1,"防具等级"=1},x=-63,y=171,z=-63,dx=126,dy=33,dz=126] slot.armor.feet 0 bedwars:red_team_boots_protectionII
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"红保护等级"=2}] ~~~ replaceitem entity @a[scores={"分队"=1,"防具等级"=2},x=-63,y=171,z=-63,dx=126,dy=33,dz=126] slot.armor.legs 0 bedwars:chainmail_leggings_protectionII
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"红保护等级"=2}] ~~~ replaceitem entity @a[scores={"分队"=1,"防具等级"=2},x=-63,y=171,z=-63,dx=126,dy=33,dz=126] slot.armor.feet 0 bedwars:chainmail_boots_protectionII
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"红保护等级"=2}] ~~~ replaceitem entity @a[scores={"分队"=1,"防具等级"=3},x=-63,y=171,z=-63,dx=126,dy=33,dz=126] slot.armor.legs 0 bedwars:iron_leggings_protectionII
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"红保护等级"=2}] ~~~ replaceitem entity @a[scores={"分队"=1,"防具等级"=3},x=-63,y=171,z=-63,dx=126,dy=33,dz=126] slot.armor.feet 0 bedwars:iron_boots_protectionII
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"红保护等级"=2}] ~~~ replaceitem entity @a[scores={"分队"=1,"防具等级"=4},x=-63,y=171,z=-63,dx=126,dy=33,dz=126] slot.armor.legs 0 bedwars:diamond_leggings_protectionII
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"红保护等级"=2}] ~~~ replaceitem entity @a[scores={"分队"=1,"防具等级"=4},x=-63,y=171,z=-63,dx=126,dy=33,dz=126] slot.armor.feet 0 bedwars:diamond_boots_protectionII
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"红保护等级"=3}] ~~~ replaceitem entity @a[scores={"分队"=1},x=-63,y=171,z=-63,dx=126,dy=33,dz=126] slot.armor.head 0 bedwars:red_team_helmet_protectionIII
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"红保护等级"=3}] ~~~ replaceitem entity @a[scores={"分队"=1},x=-63,y=171,z=-63,dx=126,dy=33,dz=126] slot.armor.chest 0 bedwars:red_team_chestplate_protectionIII
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"红保护等级"=3}] ~~~ replaceitem entity @a[scores={"分队"=1,"防具等级"=1},x=-63,y=171,z=-63,dx=126,dy=33,dz=126] slot.armor.legs 0 bedwars:red_team_leggings_protectionIII
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"红保护等级"=3}] ~~~ replaceitem entity @a[scores={"分队"=1,"防具等级"=1},x=-63,y=171,z=-63,dx=126,dy=33,dz=126] slot.armor.feet 0 bedwars:red_team_boots_protectionIII
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"红保护等级"=3}] ~~~ replaceitem entity @a[scores={"分队"=1,"防具等级"=2},x=-63,y=171,z=-63,dx=126,dy=33,dz=126] slot.armor.legs 0 bedwars:chainmail_leggings_protectionIII
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"红保护等级"=3}] ~~~ replaceitem entity @a[scores={"分队"=1,"防具等级"=2},x=-63,y=171,z=-63,dx=126,dy=33,dz=126] slot.armor.feet 0 bedwars:chainmail_boots_protectionIII
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"红保护等级"=3}] ~~~ replaceitem entity @a[scores={"分队"=1,"防具等级"=3},x=-63,y=171,z=-63,dx=126,dy=33,dz=126] slot.armor.legs 0 bedwars:iron_leggings_protectionIII
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"红保护等级"=3}] ~~~ replaceitem entity @a[scores={"分队"=1,"防具等级"=3},x=-63,y=171,z=-63,dx=126,dy=33,dz=126] slot.armor.feet 0 bedwars:iron_boots_protectionIII
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"红保护等级"=3}] ~~~ replaceitem entity @a[scores={"分队"=1,"防具等级"=4},x=-63,y=171,z=-63,dx=126,dy=33,dz=126] slot.armor.legs 0 bedwars:diamond_leggings_protectionIII
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"红保护等级"=3}] ~~~ replaceitem entity @a[scores={"分队"=1,"防具等级"=4},x=-63,y=171,z=-63,dx=126,dy=33,dz=126] slot.armor.feet 0 bedwars:diamond_boots_protectionIII
#蓝保护
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"蓝保护等级"=1}] ~~~ replaceitem entity @a[scores={"分队"=2},x=-63,y=171,z=-63,dx=126,dy=33,dz=126] slot.armor.head 0 bedwars:blue_team_helmet_protectionI
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"蓝保护等级"=1}] ~~~ replaceitem entity @a[scores={"分队"=2},x=-63,y=171,z=-63,dx=126,dy=33,dz=126] slot.armor.chest 0 bedwars:blue_team_chestplate_protectionI
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"蓝保护等级"=1}] ~~~ replaceitem entity @a[scores={"分队"=2,"防具等级"=1},x=-63,y=171,z=-63,dx=126,dy=33,dz=126] slot.armor.legs 0 bedwars:blue_team_leggings_protectionI
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"蓝保护等级"=1}] ~~~ replaceitem entity @a[scores={"分队"=2,"防具等级"=1},x=-63,y=171,z=-63,dx=126,dy=33,dz=126] slot.armor.feet 0 bedwars:blue_team_boots_protectionI
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"蓝保护等级"=1}] ~~~ replaceitem entity @a[scores={"分队"=2,"防具等级"=2},x=-63,y=171,z=-63,dx=126,dy=33,dz=126] slot.armor.legs 0 bedwars:chainmail_leggings_protectionI
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"蓝保护等级"=1}] ~~~ replaceitem entity @a[scores={"分队"=2,"防具等级"=2},x=-63,y=171,z=-63,dx=126,dy=33,dz=126] slot.armor.feet 0 bedwars:chainmail_boots_protectionI
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"蓝保护等级"=1}] ~~~ replaceitem entity @a[scores={"分队"=2,"防具等级"=3},x=-63,y=171,z=-63,dx=126,dy=33,dz=126] slot.armor.legs 0 bedwars:iron_leggings_protectionI
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"蓝保护等级"=1}] ~~~ replaceitem entity @a[scores={"分队"=2,"防具等级"=3},x=-63,y=171,z=-63,dx=126,dy=33,dz=126] slot.armor.feet 0 bedwars:iron_boots_protectionI
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"蓝保护等级"=1}] ~~~ replaceitem entity @a[scores={"分队"=2,"防具等级"=4},x=-63,y=171,z=-63,dx=126,dy=33,dz=126] slot.armor.legs 0 bedwars:diamond_leggings_protectionI
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"蓝保护等级"=1}] ~~~ replaceitem entity @a[scores={"分队"=2,"防具等级"=4},x=-63,y=171,z=-63,dx=126,dy=33,dz=126] slot.armor.feet 0 bedwars:diamond_boots_protectionI
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"蓝保护等级"=2}] ~~~ replaceitem entity @a[scores={"分队"=2},x=-63,y=171,z=-63,dx=126,dy=33,dz=126] slot.armor.head 0 bedwars:blue_team_helmet_protectionII
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"蓝保护等级"=2}] ~~~ replaceitem entity @a[scores={"分队"=2},x=-63,y=171,z=-63,dx=126,dy=33,dz=126] slot.armor.chest 0 bedwars:blue_team_chestplate_protectionII
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"蓝保护等级"=2}] ~~~ replaceitem entity @a[scores={"分队"=2,"防具等级"=1},x=-63,y=171,z=-63,dx=126,dy=33,dz=126] slot.armor.legs 0 bedwars:blue_team_leggings_protectionII
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"蓝保护等级"=2}] ~~~ replaceitem entity @a[scores={"分队"=2,"防具等级"=1},x=-63,y=171,z=-63,dx=126,dy=33,dz=126] slot.armor.feet 0 bedwars:blue_team_boots_protectionII
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"蓝保护等级"=2}] ~~~ replaceitem entity @a[scores={"分队"=2,"防具等级"=2},x=-63,y=171,z=-63,dx=126,dy=33,dz=126] slot.armor.legs 0 bedwars:chainmail_leggings_protectionII
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"蓝保护等级"=2}] ~~~ replaceitem entity @a[scores={"分队"=2,"防具等级"=2},x=-63,y=171,z=-63,dx=126,dy=33,dz=126] slot.armor.feet 0 bedwars:chainmail_boots_protectionII
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"蓝保护等级"=2}] ~~~ replaceitem entity @a[scores={"分队"=2,"防具等级"=3},x=-63,y=171,z=-63,dx=126,dy=33,dz=126] slot.armor.legs 0 bedwars:iron_leggings_protectionII
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"蓝保护等级"=2}] ~~~ replaceitem entity @a[scores={"分队"=2,"防具等级"=3},x=-63,y=171,z=-63,dx=126,dy=33,dz=126] slot.armor.feet 0 bedwars:iron_boots_protectionII
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"蓝保护等级"=2}] ~~~ replaceitem entity @a[scores={"分队"=2,"防具等级"=4},x=-63,y=171,z=-63,dx=126,dy=33,dz=126] slot.armor.legs 0 bedwars:diamond_leggings_protectionII
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"蓝保护等级"=2}] ~~~ replaceitem entity @a[scores={"分队"=2,"防具等级"=4},x=-63,y=171,z=-63,dx=126,dy=33,dz=126] slot.armor.feet 0 bedwars:diamond_boots_protectionII
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"蓝保护等级"=3}] ~~~ replaceitem entity @a[scores={"分队"=2},x=-63,y=171,z=-63,dx=126,dy=33,dz=126] slot.armor.head 0 bedwars:blue_team_helmet_protectionIII
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"蓝保护等级"=3}] ~~~ replaceitem entity @a[scores={"分队"=2},x=-63,y=171,z=-63,dx=126,dy=33,dz=126] slot.armor.chest 0 bedwars:blue_team_chestplate_protectionIII
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"蓝保护等级"=3}] ~~~ replaceitem entity @a[scores={"分队"=2,"防具等级"=1},x=-63,y=171,z=-63,dx=126,dy=33,dz=126] slot.armor.legs 0 bedwars:blue_team_leggings_protectionIII
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"蓝保护等级"=3}] ~~~ replaceitem entity @a[scores={"分队"=2,"防具等级"=1},x=-63,y=171,z=-63,dx=126,dy=33,dz=126] slot.armor.feet 0 bedwars:blue_team_boots_protectionIII
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"蓝保护等级"=3}] ~~~ replaceitem entity @a[scores={"分队"=2,"防具等级"=2},x=-63,y=171,z=-63,dx=126,dy=33,dz=126] slot.armor.legs 0 bedwars:chainmail_leggings_protectionIII
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"蓝保护等级"=3}] ~~~ replaceitem entity @a[scores={"分队"=2,"防具等级"=2},x=-63,y=171,z=-63,dx=126,dy=33,dz=126] slot.armor.feet 0 bedwars:chainmail_boots_protectionIII
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"蓝保护等级"=3}] ~~~ replaceitem entity @a[scores={"分队"=2,"防具等级"=3},x=-63,y=171,z=-63,dx=126,dy=33,dz=126] slot.armor.legs 0 bedwars:iron_leggings_protectionIII
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"蓝保护等级"=3}] ~~~ replaceitem entity @a[scores={"分队"=2,"防具等级"=3},x=-63,y=171,z=-63,dx=126,dy=33,dz=126] slot.armor.feet 0 bedwars:iron_boots_protectionIII
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"蓝保护等级"=3}] ~~~ replaceitem entity @a[scores={"分队"=2,"防具等级"=4},x=-63,y=171,z=-63,dx=126,dy=33,dz=126] slot.armor.legs 0 bedwars:diamond_leggings_protectionIII
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"蓝保护等级"=3}] ~~~ replaceitem entity @a[scores={"分队"=2,"防具等级"=4},x=-63,y=171,z=-63,dx=126,dy=33,dz=126] slot.armor.feet 0 bedwars:diamond_boots_protectionIII
#黄保护
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"黄保护等级"=1}] ~~~ replaceitem entity @a[scores={"分队"=3},x=-63,y=171,z=-63,dx=126,dy=33,dz=126] slot.armor.head 0 bedwars:yellow_team_helmet_protectionI
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"黄保护等级"=1}] ~~~ replaceitem entity @a[scores={"分队"=3},x=-63,y=171,z=-63,dx=126,dy=33,dz=126] slot.armor.chest 0 bedwars:yellow_team_chestplate_protectionI
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"黄保护等级"=1}] ~~~ replaceitem entity @a[scores={"分队"=3,"防具等级"=1},x=-63,y=171,z=-63,dx=126,dy=33,dz=126] slot.armor.legs 0 bedwars:yellow_team_leggings_protectionI
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"黄保护等级"=1}] ~~~ replaceitem entity @a[scores={"分队"=3,"防具等级"=1},x=-63,y=171,z=-63,dx=126,dy=33,dz=126] slot.armor.feet 0 bedwars:yellow_team_boots_protectionI
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"黄保护等级"=1}] ~~~ replaceitem entity @a[scores={"分队"=3,"防具等级"=2},x=-63,y=171,z=-63,dx=126,dy=33,dz=126] slot.armor.legs 0 bedwars:chainmail_leggings_protectionI
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"黄保护等级"=1}] ~~~ replaceitem entity @a[scores={"分队"=3,"防具等级"=2},x=-63,y=171,z=-63,dx=126,dy=33,dz=126] slot.armor.feet 0 bedwars:chainmail_boots_protectionI
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"黄保护等级"=1}] ~~~ replaceitem entity @a[scores={"分队"=3,"防具等级"=3},x=-63,y=171,z=-63,dx=126,dy=33,dz=126] slot.armor.legs 0 bedwars:iron_leggings_protectionI
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"黄保护等级"=1}] ~~~ replaceitem entity @a[scores={"分队"=3,"防具等级"=3},x=-63,y=171,z=-63,dx=126,dy=33,dz=126] slot.armor.feet 0 bedwars:iron_boots_protectionI
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"黄保护等级"=1}] ~~~ replaceitem entity @a[scores={"分队"=3,"防具等级"=4},x=-63,y=171,z=-63,dx=126,dy=33,dz=126] slot.armor.legs 0 bedwars:diamond_leggings_protectionI
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"黄保护等级"=1}] ~~~ replaceitem entity @a[scores={"分队"=3,"防具等级"=4},x=-63,y=171,z=-63,dx=126,dy=33,dz=126] slot.armor.feet 0 bedwars:diamond_boots_protectionI
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"黄保护等级"=2}] ~~~ replaceitem entity @a[scores={"分队"=3},x=-63,y=171,z=-63,dx=126,dy=33,dz=126] slot.armor.head 0 bedwars:yellow_team_helmet_protectionII
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"黄保护等级"=2}] ~~~ replaceitem entity @a[scores={"分队"=3},x=-63,y=171,z=-63,dx=126,dy=33,dz=126] slot.armor.chest 0 bedwars:yellow_team_chestplate_protectionII
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"黄保护等级"=2}] ~~~ replaceitem entity @a[scores={"分队"=3,"防具等级"=1},x=-63,y=171,z=-63,dx=126,dy=33,dz=126] slot.armor.legs 0 bedwars:yellow_team_leggings_protectionII
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"黄保护等级"=2}] ~~~ replaceitem entity @a[scores={"分队"=3,"防具等级"=1},x=-63,y=171,z=-63,dx=126,dy=33,dz=126] slot.armor.feet 0 bedwars:yellow_team_boots_protectionII
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"黄保护等级"=2}] ~~~ replaceitem entity @a[scores={"分队"=3,"防具等级"=2},x=-63,y=171,z=-63,dx=126,dy=33,dz=126] slot.armor.legs 0 bedwars:chainmail_leggings_protectionII
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"黄保护等级"=2}] ~~~ replaceitem entity @a[scores={"分队"=3,"防具等级"=2},x=-63,y=171,z=-63,dx=126,dy=33,dz=126] slot.armor.feet 0 bedwars:chainmail_boots_protectionII
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"黄保护等级"=2}] ~~~ replaceitem entity @a[scores={"分队"=3,"防具等级"=3},x=-63,y=171,z=-63,dx=126,dy=33,dz=126] slot.armor.legs 0 bedwars:iron_leggings_protectionII
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"黄保护等级"=2}] ~~~ replaceitem entity @a[scores={"分队"=3,"防具等级"=3},x=-63,y=171,z=-63,dx=126,dy=33,dz=126] slot.armor.feet 0 bedwars:iron_boots_protectionII
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"黄保护等级"=2}] ~~~ replaceitem entity @a[scores={"分队"=3,"防具等级"=4},x=-63,y=171,z=-63,dx=126,dy=33,dz=126] slot.armor.legs 0 bedwars:diamond_leggings_protectionII
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"黄保护等级"=2}] ~~~ replaceitem entity @a[scores={"分队"=3,"防具等级"=4},x=-63,y=171,z=-63,dx=126,dy=33,dz=126] slot.armor.feet 0 bedwars:diamond_boots_protectionII
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"黄保护等级"=3}] ~~~ replaceitem entity @a[scores={"分队"=3},x=-63,y=171,z=-63,dx=126,dy=33,dz=126] slot.armor.head 0 bedwars:yellow_team_helmet_protectionIII
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"黄保护等级"=3}] ~~~ replaceitem entity @a[scores={"分队"=3},x=-63,y=171,z=-63,dx=126,dy=33,dz=126] slot.armor.chest 0 bedwars:yellow_team_chestplate_protectionIII
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"黄保护等级"=3}] ~~~ replaceitem entity @a[scores={"分队"=3,"防具等级"=1},x=-63,y=171,z=-63,dx=126,dy=33,dz=126] slot.armor.legs 0 bedwars:yellow_team_leggings_protectionIII
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"黄保护等级"=3}] ~~~ replaceitem entity @a[scores={"分队"=3,"防具等级"=1},x=-63,y=171,z=-63,dx=126,dy=33,dz=126] slot.armor.feet 0 bedwars:yellow_team_boots_protectionIII
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"黄保护等级"=3}] ~~~ replaceitem entity @a[scores={"分队"=3,"防具等级"=2},x=-63,y=171,z=-63,dx=126,dy=33,dz=126] slot.armor.legs 0 bedwars:chainmail_leggings_protectionIII
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"黄保护等级"=3}] ~~~ replaceitem entity @a[scores={"分队"=3,"防具等级"=2},x=-63,y=171,z=-63,dx=126,dy=33,dz=126] slot.armor.feet 0 bedwars:chainmail_boots_protectionIII
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"黄保护等级"=3}] ~~~ replaceitem entity @a[scores={"分队"=3,"防具等级"=3},x=-63,y=171,z=-63,dx=126,dy=33,dz=126] slot.armor.legs 0 bedwars:iron_leggings_protectionIII
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"黄保护等级"=3}] ~~~ replaceitem entity @a[scores={"分队"=3,"防具等级"=3},x=-63,y=171,z=-63,dx=126,dy=33,dz=126] slot.armor.feet 0 bedwars:iron_boots_protectionIII
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"黄保护等级"=3}] ~~~ replaceitem entity @a[scores={"分队"=3,"防具等级"=4},x=-63,y=171,z=-63,dx=126,dy=33,dz=126] slot.armor.legs 0 bedwars:diamond_leggings_protectionIII
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"黄保护等级"=3}] ~~~ replaceitem entity @a[scores={"分队"=3,"防具等级"=4},x=-63,y=171,z=-63,dx=126,dy=33,dz=126] slot.armor.feet 0 bedwars:diamond_boots_protectionIII
#绿保护
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"绿保护等级"=1}] ~~~ replaceitem entity @a[scores={"分队"=4},x=-63,y=171,z=-63,dx=126,dy=33,dz=126] slot.armor.head 0 bedwars:green_team_helmet_protectionI
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"绿保护等级"=1}] ~~~ replaceitem entity @a[scores={"分队"=4},x=-63,y=171,z=-63,dx=126,dy=33,dz=126] slot.armor.chest 0 bedwars:green_team_chestplate_protectionI
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"绿保护等级"=1}] ~~~ replaceitem entity @a[scores={"分队"=4,"防具等级"=1},x=-63,y=171,z=-63,dx=126,dy=33,dz=126] slot.armor.legs 0 bedwars:green_team_leggings_protectionI 
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"绿保护等级"=1}] ~~~ replaceitem entity @a[scores={"分队"=4,"防具等级"=1},x=-63,y=171,z=-63,dx=126,dy=33,dz=126] slot.armor.feet 0 bedwars:green_team_boots_protectionI
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"绿保护等级"=1}] ~~~ replaceitem entity @a[scores={"分队"=4,"防具等级"=2},x=-63,y=171,z=-63,dx=126,dy=33,dz=126] slot.armor.legs 0 bedwars:chainmail_leggings_protectionI
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"绿保护等级"=1}] ~~~ replaceitem entity @a[scores={"分队"=4,"防具等级"=2},x=-63,y=171,z=-63,dx=126,dy=33,dz=126] slot.armor.feet 0 bedwars:chainmail_boots_protectionI
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"绿保护等级"=1}] ~~~ replaceitem entity @a[scores={"分队"=4,"防具等级"=3},x=-63,y=171,z=-63,dx=126,dy=33,dz=126] slot.armor.legs 0 bedwars:iron_leggings_protectionI
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"绿保护等级"=1}] ~~~ replaceitem entity @a[scores={"分队"=4,"防具等级"=3},x=-63,y=171,z=-63,dx=126,dy=33,dz=126] slot.armor.feet 0 bedwars:iron_boots_protectionI
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"绿保护等级"=1}] ~~~ replaceitem entity @a[scores={"分队"=4,"防具等级"=4},x=-63,y=171,z=-63,dx=126,dy=33,dz=126] slot.armor.legs 0 bedwars:diamond_leggings_protectionI
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"绿保护等级"=1}] ~~~ replaceitem entity @a[scores={"分队"=4,"防具等级"=4},x=-63,y=171,z=-63,dx=126,dy=33,dz=126] slot.armor.feet 0 bedwars:diamond_boots_protectionI
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"绿保护等级"=2}] ~~~ replaceitem entity @a[scores={"分队"=4},x=-63,y=171,z=-63,dx=126,dy=33,dz=126] slot.armor.head 0 bedwars:green_team_helmet_protectionII
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"绿保护等级"=2}] ~~~ replaceitem entity @a[scores={"分队"=4},x=-63,y=171,z=-63,dx=126,dy=33,dz=126] slot.armor.chest 0 bedwars:green_team_chestplate_protectionII
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"绿保护等级"=2}] ~~~ replaceitem entity @a[scores={"分队"=4,"防具等级"=1},x=-63,y=171,z=-63,dx=126,dy=33,dz=126] slot.armor.legs 0 bedwars:green_team_leggings_protectionII
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"绿保护等级"=2}] ~~~ replaceitem entity @a[scores={"分队"=4,"防具等级"=1},x=-63,y=171,z=-63,dx=126,dy=33,dz=126] slot.armor.feet 0 bedwars:green_team_boots_protectionII
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"绿保护等级"=2}] ~~~ replaceitem entity @a[scores={"分队"=4,"防具等级"=2},x=-63,y=171,z=-63,dx=126,dy=33,dz=126] slot.armor.legs 0 bedwars:chainmail_leggings_protectionII
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"绿保护等级"=2}] ~~~ replaceitem entity @a[scores={"分队"=4,"防具等级"=2},x=-63,y=171,z=-63,dx=126,dy=33,dz=126] slot.armor.feet 0 bedwars:chainmail_boots_protectionII
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"绿保护等级"=2}] ~~~ replaceitem entity @a[scores={"分队"=4,"防具等级"=3},x=-63,y=171,z=-63,dx=126,dy=33,dz=126] slot.armor.legs 0 bedwars:iron_leggings_protectionII
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"绿保护等级"=2}] ~~~ replaceitem entity @a[scores={"分队"=4,"防具等级"=3},x=-63,y=171,z=-63,dx=126,dy=33,dz=126] slot.armor.feet 0 bedwars:iron_boots_protectionII
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"绿保护等级"=2}] ~~~ replaceitem entity @a[scores={"分队"=4,"防具等级"=4},x=-63,y=171,z=-63,dx=126,dy=33,dz=126] slot.armor.legs 0 bedwars:diamond_leggings_protectionII
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"绿保护等级"=2}] ~~~ replaceitem entity @a[scores={"分队"=4,"防具等级"=4},x=-63,y=171,z=-63,dx=126,dy=33,dz=126] slot.armor.feet 0 bedwars:diamond_boots_protectionII
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"绿保护等级"=3}] ~~~ replaceitem entity @a[scores={"分队"=4},x=-63,y=171,z=-63,dx=126,dy=33,dz=126] slot.armor.head 0 bedwars:green_team_helmet_protectionIII
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"绿保护等级"=3}] ~~~ replaceitem entity @a[scores={"分队"=4},x=-63,y=171,z=-63,dx=126,dy=33,dz=126] slot.armor.chest 0 bedwars:green_team_chestplate_protectionIII
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"绿保护等级"=3}] ~~~ replaceitem entity @a[scores={"分队"=4,"防具等级"=1},x=-63,y=171,z=-63,dx=126,dy=33,dz=126] slot.armor.legs 0 bedwars:green_team_leggings_protectionIII
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"绿保护等级"=3}] ~~~ replaceitem entity @a[scores={"分队"=4,"防具等级"=1},x=-63,y=171,z=-63,dx=126,dy=33,dz=126] slot.armor.feet 0 bedwars:green_team_boots_protectionIII
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"绿保护等级"=3}] ~~~ replaceitem entity @a[scores={"分队"=4,"防具等级"=2},x=-63,y=171,z=-63,dx=126,dy=33,dz=126] slot.armor.legs 0 bedwars:chainmail_leggings_protectionIII
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"绿保护等级"=3}] ~~~ replaceitem entity @a[scores={"分队"=4,"防具等级"=2},x=-63,y=171,z=-63,dx=126,dy=33,dz=126] slot.armor.feet 0 bedwars:chainmail_boots_protectionIII
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"绿保护等级"=3}] ~~~ replaceitem entity @a[scores={"分队"=4,"防具等级"=3},x=-63,y=171,z=-63,dx=126,dy=33,dz=126] slot.armor.legs 0 bedwars:iron_leggings_protectionIII
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"绿保护等级"=3}] ~~~ replaceitem entity @a[scores={"分队"=4,"防具等级"=3},x=-63,y=171,z=-63,dx=126,dy=33,dz=126] slot.armor.feet 0 bedwars:iron_boots_protectionIII
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"绿保护等级"=3}] ~~~ replaceitem entity @a[scores={"分队"=4,"防具等级"=4},x=-63,y=171,z=-63,dx=126,dy=33,dz=126] slot.armor.legs 0 bedwars:diamond_leggings_protectionIII
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"绿保护等级"=3}] ~~~ replaceitem entity @a[scores={"分队"=4,"防具等级"=4},x=-63,y=171,z=-63,dx=126,dy=33,dz=126] slot.armor.feet 0 bedwars:diamond_boots_protectionIII

#红锋利
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"红锋利等级"=1}] ~~~ tag @a[scores={"分队"=1},x=-63,y=171,z=-63,dx=126,dy=33,dz=126,tag=!have_upgraded_sword_sharpnessI] add clear_wooden_sword
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"红锋利等级"=1}] ~~~ tag @a[scores={"分队"=1},x=-63,y=171,z=-63,dx=126,dy=33,dz=126,tag=!have_upgraded_sword_sharpnessI] add clear_stone_sword
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"红锋利等级"=1}] ~~~ tag @a[scores={"分队"=1},x=-63,y=171,z=-63,dx=126,dy=33,dz=126,tag=!have_upgraded_sword_sharpnessI] add clear_iron_sword
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"红锋利等级"=1}] ~~~ tag @a[scores={"分队"=1},x=-63,y=171,z=-63,dx=126,dy=33,dz=126,tag=!have_upgraded_sword_sharpnessI] add clear_diamond_sword
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"红锋利等级"=1}] ~~~ tag @a[scores={"分队"=1,"剑等级"=1},x=-63,y=171,z=-63,dx=126,dy=33,dz=126,tag=!have_upgraded_sword_sharpnessI] add give_wooden_sword_sharpnessI
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"红锋利等级"=1}] ~~~ tag @a[scores={"分队"=1,"剑等级"=2},x=-63,y=171,z=-63,dx=126,dy=33,dz=126,tag=!have_upgraded_sword_sharpnessI] add give_stone_sword_sharpnessI
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"红锋利等级"=1}] ~~~ tag @a[scores={"分队"=1,"剑等级"=3},x=-63,y=171,z=-63,dx=126,dy=33,dz=126,tag=!have_upgraded_sword_sharpnessI] add give_iron_sword_sharpnessI
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"红锋利等级"=1}] ~~~ tag @a[scores={"分队"=1,"剑等级"=4},x=-63,y=171,z=-63,dx=126,dy=33,dz=126,tag=!have_upgraded_sword_sharpnessI] add give_diamond_sword_sharpnessI
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"红锋利等级"=1}] ~~~ tag @a[scores={"分队"=1}] add have_upgraded_sword_sharpnessI
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"红锋利等级"=2}] ~~~ tag @a[scores={"分队"=1},x=-63,y=171,z=-63,dx=126,dy=33,dz=126,tag=!have_upgraded_sword_sharpnessII] add clear_wooden_sword_sharpnessI
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"红锋利等级"=2}] ~~~ tag @a[scores={"分队"=1},x=-63,y=171,z=-63,dx=126,dy=33,dz=126,tag=!have_upgraded_sword_sharpnessII] add clear_stone_sword_sharpnessI
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"红锋利等级"=2}] ~~~ tag @a[scores={"分队"=1},x=-63,y=171,z=-63,dx=126,dy=33,dz=126,tag=!have_upgraded_sword_sharpnessII] add clear_iron_sword_sharpnessI
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"红锋利等级"=2}] ~~~ tag @a[scores={"分队"=1},x=-63,y=171,z=-63,dx=126,dy=33,dz=126,tag=!have_upgraded_sword_sharpnessII] add clear_diamond_sword_sharpnessI
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"红锋利等级"=2}] ~~~ tag @a[scores={"分队"=1,"剑等级"=1},x=-63,y=171,z=-63,dx=126,dy=33,dz=126,tag=!have_upgraded_sword_sharpnessII] add give_wooden_sword_sharpnessII
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"红锋利等级"=2}] ~~~ tag @a[scores={"分队"=1,"剑等级"=2},x=-63,y=171,z=-63,dx=126,dy=33,dz=126,tag=!have_upgraded_sword_sharpnessII] add give_stone_sword_sharpnessII
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"红锋利等级"=2}] ~~~ tag @a[scores={"分队"=1,"剑等级"=3},x=-63,y=171,z=-63,dx=126,dy=33,dz=126,tag=!have_upgraded_sword_sharpnessII] add give_iron_sword_sharpnessII
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"红锋利等级"=2}] ~~~ tag @a[scores={"分队"=1,"剑等级"=4},x=-63,y=171,z=-63,dx=126,dy=33,dz=126,tag=!have_upgraded_sword_sharpnessII] add give_diamond_sword_sharpnessII
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"红锋利等级"=2}] ~~~ tag @a[scores={"分队"=1}] add have_upgraded_sword_sharpnessII
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"红锋利等级"=3}] ~~~ tag @a[scores={"分队"=1},x=-63,y=171,z=-63,dx=126,dy=33,dz=126,tag=!have_upgraded_sword_sharpnessIII] add clear_wooden_sword_sharpnessII
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"红锋利等级"=3}] ~~~ tag @a[scores={"分队"=1},x=-63,y=171,z=-63,dx=126,dy=33,dz=126,tag=!have_upgraded_sword_sharpnessIII] add clear_stone_sword_sharpnessII
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"红锋利等级"=3}] ~~~ tag @a[scores={"分队"=1},x=-63,y=171,z=-63,dx=126,dy=33,dz=126,tag=!have_upgraded_sword_sharpnessIII] add clear_iron_sword_sharpnessII
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"红锋利等级"=3}] ~~~ tag @a[scores={"分队"=1},x=-63,y=171,z=-63,dx=126,dy=33,dz=126,tag=!have_upgraded_sword_sharpnessIII] add clear_diamond_sword_sharpnessII
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"红锋利等级"=3}] ~~~ tag @a[scores={"分队"=1,"剑等级"=1},x=-63,y=171,z=-63,dx=126,dy=33,dz=126,tag=!have_upgraded_sword_sharpnessIII] add give_wooden_sword_sharpnessIII
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"红锋利等级"=3}] ~~~ tag @a[scores={"分队"=1,"剑等级"=2},x=-63,y=171,z=-63,dx=126,dy=33,dz=126,tag=!have_upgraded_sword_sharpnessIII] add give_stone_sword_sharpnessIII
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"红锋利等级"=3}] ~~~ tag @a[scores={"分队"=1,"剑等级"=3},x=-63,y=171,z=-63,dx=126,dy=33,dz=126,tag=!have_upgraded_sword_sharpnessIII] add give_iron_sword_sharpnessIII
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"红锋利等级"=3}] ~~~ tag @a[scores={"分队"=1,"剑等级"=4},x=-63,y=171,z=-63,dx=126,dy=33,dz=126,tag=!have_upgraded_sword_sharpnessIII] add give_diamond_sword_sharpnessIII
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"红锋利等级"=3}] ~~~ tag @a[scores={"分队"=1}] add have_upgraded_sword_sharpnessIII
#蓝锋利
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"蓝锋利等级"=1}] ~~~ tag @a[scores={"分队"=2},x=-63,y=171,z=-63,dx=126,dy=33,dz=126,tag=!have_upgraded_sword_sharpnessI] add clear_wooden_sword
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"蓝锋利等级"=1}] ~~~ tag @a[scores={"分队"=2},x=-63,y=171,z=-63,dx=126,dy=33,dz=126,tag=!have_upgraded_sword_sharpnessI] add clear_stone_sword
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"蓝锋利等级"=1}] ~~~ tag @a[scores={"分队"=2},x=-63,y=171,z=-63,dx=126,dy=33,dz=126,tag=!have_upgraded_sword_sharpnessI] add clear_iron_sword
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"蓝锋利等级"=1}] ~~~ tag @a[scores={"分队"=2},x=-63,y=171,z=-63,dx=126,dy=33,dz=126,tag=!have_upgraded_sword_sharpnessI] add clear_diamond_sword
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"蓝锋利等级"=1}] ~~~ tag @a[scores={"分队"=2,"剑等级"=1},x=-63,y=171,z=-63,dx=126,dy=33,dz=126,tag=!have_upgraded_sword_sharpnessI] add give_wooden_sword_sharpnessI
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"蓝锋利等级"=1}] ~~~ tag @a[scores={"分队"=2,"剑等级"=2},x=-63,y=171,z=-63,dx=126,dy=33,dz=126,tag=!have_upgraded_sword_sharpnessI] add give_stone_sword_sharpnessI
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"蓝锋利等级"=1}] ~~~ tag @a[scores={"分队"=2,"剑等级"=3},x=-63,y=171,z=-63,dx=126,dy=33,dz=126,tag=!have_upgraded_sword_sharpnessI] add give_iron_sword_sharpnessI
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"蓝锋利等级"=1}] ~~~ tag @a[scores={"分队"=2,"剑等级"=4},x=-63,y=171,z=-63,dx=126,dy=33,dz=126,tag=!have_upgraded_sword_sharpnessI] add give_diamond_sword_sharpnessI
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"蓝锋利等级"=1}] ~~~ tag @a[scores={"分队"=2}] add have_upgraded_sword_sharpnessI
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"蓝锋利等级"=2}] ~~~ tag @a[scores={"分队"=2},x=-63,y=171,z=-63,dx=126,dy=33,dz=126,tag=!have_upgraded_sword_sharpnessII] add clear_wooden_sword_sharpnessI
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"蓝锋利等级"=2}] ~~~ tag @a[scores={"分队"=2},x=-63,y=171,z=-63,dx=126,dy=33,dz=126,tag=!have_upgraded_sword_sharpnessII] add clear_stone_sword_sharpnessI
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"蓝锋利等级"=2}] ~~~ tag @a[scores={"分队"=2},x=-63,y=171,z=-63,dx=126,dy=33,dz=126,tag=!have_upgraded_sword_sharpnessII] add clear_iron_sword_sharpnessI
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"蓝锋利等级"=2}] ~~~ tag @a[scores={"分队"=2},x=-63,y=171,z=-63,dx=126,dy=33,dz=126,tag=!have_upgraded_sword_sharpnessII] add clear_diamond_sword_sharpnessI
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"蓝锋利等级"=2}] ~~~ tag @a[scores={"分队"=2,"剑等级"=1},x=-63,y=171,z=-63,dx=126,dy=33,dz=126,tag=!have_upgraded_sword_sharpnessII] add give_wooden_sword_sharpnessII
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"蓝锋利等级"=2}] ~~~ tag @a[scores={"分队"=2,"剑等级"=2},x=-63,y=171,z=-63,dx=126,dy=33,dz=126,tag=!have_upgraded_sword_sharpnessII] add give_stone_sword_sharpnessII
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"蓝锋利等级"=2}] ~~~ tag @a[scores={"分队"=2,"剑等级"=3},x=-63,y=171,z=-63,dx=126,dy=33,dz=126,tag=!have_upgraded_sword_sharpnessII] add give_iron_sword_sharpnessII
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"蓝锋利等级"=2}] ~~~ tag @a[scores={"分队"=2,"剑等级"=4},x=-63,y=171,z=-63,dx=126,dy=33,dz=126,tag=!have_upgraded_sword_sharpnessII] add give_diamond_sword_sharpnessII
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"蓝锋利等级"=2}] ~~~ tag @a[scores={"分队"=2}] add have_upgraded_sword_sharpnessII
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"蓝锋利等级"=3}] ~~~ tag @a[scores={"分队"=2},x=-63,y=171,z=-63,dx=126,dy=33,dz=126,tag=!have_upgraded_sword_sharpnessIII] add clear_wooden_sword_sharpnessII
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"蓝锋利等级"=3}] ~~~ tag @a[scores={"分队"=2},x=-63,y=171,z=-63,dx=126,dy=33,dz=126,tag=!have_upgraded_sword_sharpnessIII] add clear_stone_sword_sharpnessII
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"蓝锋利等级"=3}] ~~~ tag @a[scores={"分队"=2},x=-63,y=171,z=-63,dx=126,dy=33,dz=126,tag=!have_upgraded_sword_sharpnessIII] add clear_iron_sword_sharpnessII
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"蓝锋利等级"=3}] ~~~ tag @a[scores={"分队"=2},x=-63,y=171,z=-63,dx=126,dy=33,dz=126,tag=!have_upgraded_sword_sharpnessIII] add clear_diamond_sword_sharpnessII
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"蓝锋利等级"=3}] ~~~ tag @a[scores={"分队"=2,"剑等级"=1},x=-63,y=171,z=-63,dx=126,dy=33,dz=126,tag=!have_upgraded_sword_sharpnessIII] add give_wooden_sword_sharpnessIII
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"蓝锋利等级"=3}] ~~~ tag @a[scores={"分队"=2,"剑等级"=2},x=-63,y=171,z=-63,dx=126,dy=33,dz=126,tag=!have_upgraded_sword_sharpnessIII] add give_stone_sword_sharpnessIII
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"蓝锋利等级"=3}] ~~~ tag @a[scores={"分队"=2,"剑等级"=3},x=-63,y=171,z=-63,dx=126,dy=33,dz=126,tag=!have_upgraded_sword_sharpnessIII] add give_iron_sword_sharpnessIII
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"蓝锋利等级"=3}] ~~~ tag @a[scores={"分队"=2,"剑等级"=4},x=-63,y=171,z=-63,dx=126,dy=33,dz=126,tag=!have_upgraded_sword_sharpnessIII] add give_diamond_sword_sharpnessIII
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"蓝锋利等级"=3}] ~~~ tag @a[scores={"分队"=2}] add have_upgraded_sword_sharpnessIII
#黄锋利
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"黄锋利等级"=1}] ~~~ tag @a[scores={"分队"=3},x=-63,y=171,z=-63,dx=126,dy=33,dz=126,tag=!have_upgraded_sword_sharpnessI] add clear_wooden_sword
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"黄锋利等级"=1}] ~~~ tag @a[scores={"分队"=3},x=-63,y=171,z=-63,dx=126,dy=33,dz=126,tag=!have_upgraded_sword_sharpnessI] add clear_stone_sword
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"黄锋利等级"=1}] ~~~ tag @a[scores={"分队"=3},x=-63,y=171,z=-63,dx=126,dy=33,dz=126,tag=!have_upgraded_sword_sharpnessI] add clear_iron_sword
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"黄锋利等级"=1}] ~~~ tag @a[scores={"分队"=3},x=-63,y=171,z=-63,dx=126,dy=33,dz=126,tag=!have_upgraded_sword_sharpnessI] add clear_diamond_sword
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"黄锋利等级"=1}] ~~~ tag @a[scores={"分队"=3,"剑等级"=1},x=-63,y=171,z=-63,dx=126,dy=33,dz=126,tag=!have_upgraded_sword_sharpnessI] add give_wooden_sword_sharpnessI
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"黄锋利等级"=1}] ~~~ tag @a[scores={"分队"=3,"剑等级"=2},x=-63,y=171,z=-63,dx=126,dy=33,dz=126,tag=!have_upgraded_sword_sharpnessI] add give_stone_sword_sharpnessI
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"黄锋利等级"=1}] ~~~ tag @a[scores={"分队"=3,"剑等级"=3},x=-63,y=171,z=-63,dx=126,dy=33,dz=126,tag=!have_upgraded_sword_sharpnessI] add give_iron_sword_sharpnessI
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"黄锋利等级"=1}] ~~~ tag @a[scores={"分队"=3,"剑等级"=4},x=-63,y=171,z=-63,dx=126,dy=33,dz=126,tag=!have_upgraded_sword_sharpnessI] add give_diamond_sword_sharpnessI
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"黄锋利等级"=1}] ~~~ tag @a[scores={"分队"=3}] add have_upgraded_sword_sharpnessI
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"黄锋利等级"=2}] ~~~ tag @a[scores={"分队"=3},x=-63,y=171,z=-63,dx=126,dy=33,dz=126,tag=!have_upgraded_sword_sharpnessII] add clear_wooden_sword_sharpnessI
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"黄锋利等级"=2}] ~~~ tag @a[scores={"分队"=3},x=-63,y=171,z=-63,dx=126,dy=33,dz=126,tag=!have_upgraded_sword_sharpnessII] add clear_stone_sword_sharpnessI
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"黄锋利等级"=2}] ~~~ tag @a[scores={"分队"=3},x=-63,y=171,z=-63,dx=126,dy=33,dz=126,tag=!have_upgraded_sword_sharpnessII] add clear_iron_sword_sharpnessI
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"黄锋利等级"=2}] ~~~ tag @a[scores={"分队"=3},x=-63,y=171,z=-63,dx=126,dy=33,dz=126,tag=!have_upgraded_sword_sharpnessII] add clear_diamond_sword_sharpnessI
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"黄锋利等级"=2}] ~~~ tag @a[scores={"分队"=3,"剑等级"=1},x=-63,y=171,z=-63,dx=126,dy=33,dz=126,tag=!have_upgraded_sword_sharpnessII] add give_wooden_sword_sharpnessII
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"黄锋利等级"=2}] ~~~ tag @a[scores={"分队"=3,"剑等级"=2},x=-63,y=171,z=-63,dx=126,dy=33,dz=126,tag=!have_upgraded_sword_sharpnessII] add give_stone_sword_sharpnessII
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"黄锋利等级"=2}] ~~~ tag @a[scores={"分队"=3,"剑等级"=3},x=-63,y=171,z=-63,dx=126,dy=33,dz=126,tag=!have_upgraded_sword_sharpnessII] add give_iron_sword_sharpnessII
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"黄锋利等级"=2}] ~~~ tag @a[scores={"分队"=3,"剑等级"=4},x=-63,y=171,z=-63,dx=126,dy=33,dz=126,tag=!have_upgraded_sword_sharpnessII] add give_diamond_sword_sharpnessII
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"黄锋利等级"=2}] ~~~ tag @a[scores={"分队"=3}] add have_upgraded_sword_sharpnessII
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"黄锋利等级"=3}] ~~~ tag @a[scores={"分队"=3},x=-63,y=171,z=-63,dx=126,dy=33,dz=126,tag=!have_upgraded_sword_sharpnessIII] add clear_wooden_sword_sharpnessII
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"黄锋利等级"=3}] ~~~ tag @a[scores={"分队"=3},x=-63,y=171,z=-63,dx=126,dy=33,dz=126,tag=!have_upgraded_sword_sharpnessIII] add clear_stone_sword_sharpnessII
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"黄锋利等级"=3}] ~~~ tag @a[scores={"分队"=3},x=-63,y=171,z=-63,dx=126,dy=33,dz=126,tag=!have_upgraded_sword_sharpnessIII] add clear_iron_sword_sharpnessII
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"黄锋利等级"=3}] ~~~ tag @a[scores={"分队"=3},x=-63,y=171,z=-63,dx=126,dy=33,dz=126,tag=!have_upgraded_sword_sharpnessIII] add clear_diamond_sword_sharpnessII
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"黄锋利等级"=3}] ~~~ tag @a[scores={"分队"=3,"剑等级"=1},x=-63,y=171,z=-63,dx=126,dy=33,dz=126,tag=!have_upgraded_sword_sharpnessIII] add give_wooden_sword_sharpnessIII
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"黄锋利等级"=3}] ~~~ tag @a[scores={"分队"=3,"剑等级"=2},x=-63,y=171,z=-63,dx=126,dy=33,dz=126,tag=!have_upgraded_sword_sharpnessIII] add give_stone_sword_sharpnessIII
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"黄锋利等级"=3}] ~~~ tag @a[scores={"分队"=3,"剑等级"=3},x=-63,y=171,z=-63,dx=126,dy=33,dz=126,tag=!have_upgraded_sword_sharpnessIII] add give_iron_sword_sharpnessIII
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"黄锋利等级"=3}] ~~~ tag @a[scores={"分队"=3,"剑等级"=4},x=-63,y=171,z=-63,dx=126,dy=33,dz=126,tag=!have_upgraded_sword_sharpnessIII] add give_diamond_sword_sharpnessIII
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"黄锋利等级"=3}] ~~~ tag @a[scores={"分队"=3}] add have_upgraded_sword_sharpnessIII
#绿锋利
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"绿锋利等级"=1}] ~~~ tag @a[scores={"分队"=3},x=-63,y=171,z=-63,dx=126,dy=33,dz=126,tag=!have_upgraded_sword_sharpnessI] add clear_wooden_sword
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"绿锋利等级"=1}] ~~~ tag @a[scores={"分队"=3},x=-63,y=171,z=-63,dx=126,dy=33,dz=126,tag=!have_upgraded_sword_sharpnessI] add clear_stone_sword
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"绿锋利等级"=1}] ~~~ tag @a[scores={"分队"=3},x=-63,y=171,z=-63,dx=126,dy=33,dz=126,tag=!have_upgraded_sword_sharpnessI] add clear_iron_sword
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"绿锋利等级"=1}] ~~~ tag @a[scores={"分队"=3},x=-63,y=171,z=-63,dx=126,dy=33,dz=126,tag=!have_upgraded_sword_sharpnessI] add clear_diamond_sword
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"绿锋利等级"=1}] ~~~ tag @a[scores={"分队"=3,"剑等级"=1},x=-63,y=171,z=-63,dx=126,dy=33,dz=126,tag=!have_upgraded_sword_sharpnessI] add give_wooden_sword_sharpnessI
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"绿锋利等级"=1}] ~~~ tag @a[scores={"分队"=3,"剑等级"=2},x=-63,y=171,z=-63,dx=126,dy=33,dz=126,tag=!have_upgraded_sword_sharpnessI] add give_stone_sword_sharpnessI
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"绿锋利等级"=1}] ~~~ tag @a[scores={"分队"=3,"剑等级"=3},x=-63,y=171,z=-63,dx=126,dy=33,dz=126,tag=!have_upgraded_sword_sharpnessI] add give_iron_sword_sharpnessI
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"绿锋利等级"=1}] ~~~ tag @a[scores={"分队"=3,"剑等级"=4},x=-63,y=171,z=-63,dx=126,dy=33,dz=126,tag=!have_upgraded_sword_sharpnessI] add give_diamond_sword_sharpnessI
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"绿锋利等级"=1}] ~~~ tag @a[scores={"分队"=3}] add have_upgraded_sword_sharpnessI
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"绿锋利等级"=2}] ~~~ tag @a[scores={"分队"=3},x=-63,y=171,z=-63,dx=126,dy=33,dz=126,tag=!have_upgraded_sword_sharpnessII] add clear_wooden_sword_sharpnessI
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"绿锋利等级"=2}] ~~~ tag @a[scores={"分队"=3},x=-63,y=171,z=-63,dx=126,dy=33,dz=126,tag=!have_upgraded_sword_sharpnessII] add clear_stone_sword_sharpnessI
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"绿锋利等级"=2}] ~~~ tag @a[scores={"分队"=3},x=-63,y=171,z=-63,dx=126,dy=33,dz=126,tag=!have_upgraded_sword_sharpnessII] add clear_iron_sword_sharpnessI
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"绿锋利等级"=2}] ~~~ tag @a[scores={"分队"=3},x=-63,y=171,z=-63,dx=126,dy=33,dz=126,tag=!have_upgraded_sword_sharpnessII] add clear_diamond_sword_sharpnessI
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"绿锋利等级"=2}] ~~~ tag @a[scores={"分队"=3,"剑等级"=1},x=-63,y=171,z=-63,dx=126,dy=33,dz=126,tag=!have_upgraded_sword_sharpnessII] add give_wooden_sword_sharpnessII
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"绿锋利等级"=2}] ~~~ tag @a[scores={"分队"=3,"剑等级"=2},x=-63,y=171,z=-63,dx=126,dy=33,dz=126,tag=!have_upgraded_sword_sharpnessII] add give_stone_sword_sharpnessII
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"绿锋利等级"=2}] ~~~ tag @a[scores={"分队"=3,"剑等级"=3},x=-63,y=171,z=-63,dx=126,dy=33,dz=126,tag=!have_upgraded_sword_sharpnessII] add give_iron_sword_sharpnessII
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"绿锋利等级"=2}] ~~~ tag @a[scores={"分队"=3,"剑等级"=4},x=-63,y=171,z=-63,dx=126,dy=33,dz=126,tag=!have_upgraded_sword_sharpnessII] add give_diamond_sword_sharpnessII
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"绿锋利等级"=2}] ~~~ tag @a[scores={"分队"=3}] add have_upgraded_sword_sharpnessII
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"绿锋利等级"=3}] ~~~ tag @a[scores={"分队"=3},x=-63,y=171,z=-63,dx=126,dy=33,dz=126,tag=!have_upgraded_sword_sharpnessIII] add clear_wooden_sword_sharpnessII
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"绿锋利等级"=3}] ~~~ tag @a[scores={"分队"=3},x=-63,y=171,z=-63,dx=126,dy=33,dz=126,tag=!have_upgraded_sword_sharpnessIII] add clear_stone_sword_sharpnessII
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"绿锋利等级"=3}] ~~~ tag @a[scores={"分队"=3},x=-63,y=171,z=-63,dx=126,dy=33,dz=126,tag=!have_upgraded_sword_sharpnessIII] add clear_iron_sword_sharpnessII
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"绿锋利等级"=3}] ~~~ tag @a[scores={"分队"=3},x=-63,y=171,z=-63,dx=126,dy=33,dz=126,tag=!have_upgraded_sword_sharpnessIII] add clear_diamond_sword_sharpnessII
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"绿锋利等级"=3}] ~~~ tag @a[scores={"分队"=3,"剑等级"=1},x=-63,y=171,z=-63,dx=126,dy=33,dz=126,tag=!have_upgraded_sword_sharpnessIII] add give_wooden_sword_sharpnessIII  
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"绿锋利等级"=3}] ~~~ tag @a[scores={"分队"=3,"剑等级"=2},x=-63,y=171,z=-63,dx=126,dy=33,dz=126,tag=!have_upgraded_sword_sharpnessIII] add give_stone_sword_sharpnessIII   
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"绿锋利等级"=3}] ~~~ tag @a[scores={"分队"=3,"剑等级"=3},x=-63,y=171,z=-63,dx=126,dy=33,dz=126,tag=!have_upgraded_sword_sharpnessIII] add give_iron_sword_sharpnessIII    
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"绿锋利等级"=3}] ~~~ tag @a[scores={"分队"=3,"剑等级"=4},x=-63,y=171,z=-63,dx=126,dy=33,dz=126,tag=!have_upgraded_sword_sharpnessIII] add give_diamond_sword_sharpnessIII 
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"绿锋利等级"=3}] ~~~ tag @a[scores={"分队"=3}] add have_upgraded_sword_sharpnessIII