#红保护
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"红保护等级"=1}] ~~~ loot replace entity @a[scores={"分队"=1},x=-63,y=171,z=-63,dx=126,dy=33,dz=126] slot.armor.head 0 loot "ench_armors/ench_protection1_red_team_helmet"
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"红保护等级"=1}] ~~~ loot replace entity @a[scores={"分队"=1},x=-63,y=171,z=-63,dx=126,dy=33,dz=126] slot.armor.chest 0 loot "ench_armors/ench_protection1_red_team_chestplate"
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"红保护等级"=1}] ~~~ loot replace entity @a[scores={"分队"=1,"防具等级"=1},x=-63,y=171,z=-63,dx=126,dy=33,dz=126] slot.armor.legs 0 loot "ench_armors/ench_protection1_red_team_leggings"
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"红保护等级"=1}] ~~~ loot replace entity @a[scores={"分队"=1,"防具等级"=1},x=-63,y=171,z=-63,dx=126,dy=33,dz=126] slot.armor.feet 0 loot "ench_armors/ench_protection1_red_team_boots"
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"红保护等级"=1}] ~~~ loot replace entity @a[scores={"分队"=1,"防具等级"=2},x=-63,y=171,z=-63,dx=126,dy=33,dz=126] slot.armor.legs 0 loot "ench_armors/ench_protection1_chainmail_leggings"
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"红保护等级"=1}] ~~~ loot replace entity @a[scores={"分队"=1,"防具等级"=2},x=-63,y=171,z=-63,dx=126,dy=33,dz=126] slot.armor.feet 0 loot "ench_armors/ench_protection1_chainmail_boots"
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"红保护等级"=1}] ~~~ loot replace entity @a[scores={"分队"=1,"防具等级"=3},x=-63,y=171,z=-63,dx=126,dy=33,dz=126] slot.armor.legs 0 loot "ench_armors/ench_protection1_iron_leggings"
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"红保护等级"=1}] ~~~ loot replace entity @a[scores={"分队"=1,"防具等级"=3},x=-63,y=171,z=-63,dx=126,dy=33,dz=126] slot.armor.feet 0 loot "ench_armors/ench_protection1_iron_boots"
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"红保护等级"=1}] ~~~ loot replace entity @a[scores={"分队"=1,"防具等级"=4},x=-63,y=171,z=-63,dx=126,dy=33,dz=126] slot.armor.legs 0 loot "ench_armors/ench_protection1_diamond_leggings"
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"红保护等级"=1}] ~~~ loot replace entity @a[scores={"分队"=1,"防具等级"=4},x=-63,y=171,z=-63,dx=126,dy=33,dz=126] slot.armor.feet 0 loot "ench_armors/ench_protection1_diamond_boots"
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"红保护等级"=2}] ~~~ loot replace entity @a[scores={"分队"=1},x=-63,y=171,z=-63,dx=126,dy=33,dz=126] slot.armor.head 0 loot "ench_armors/ench_protection2_red_team_helmet"
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"红保护等级"=2}] ~~~ loot replace entity @a[scores={"分队"=1},x=-63,y=171,z=-63,dx=126,dy=33,dz=126] slot.armor.chest 0 loot "ench_armors/ench_protection2_red_team_chestplate"
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"红保护等级"=2}] ~~~ loot replace entity @a[scores={"分队"=1,"防具等级"=1},x=-63,y=171,z=-63,dx=126,dy=33,dz=126] slot.armor.legs 0 loot "ench_armors/ench_protection2_red_team_leggings"
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"红保护等级"=2}] ~~~ loot replace entity @a[scores={"分队"=1,"防具等级"=1},x=-63,y=171,z=-63,dx=126,dy=33,dz=126] slot.armor.feet 0 loot "ench_armors/ench_protection2_red_team_boots"
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"红保护等级"=2}] ~~~ loot replace entity @a[scores={"分队"=1,"防具等级"=2},x=-63,y=171,z=-63,dx=126,dy=33,dz=126] slot.armor.legs 0 loot "ench_armors/ench_protection2_chainmail_leggings"
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"红保护等级"=2}] ~~~ loot replace entity @a[scores={"分队"=1,"防具等级"=2},x=-63,y=171,z=-63,dx=126,dy=33,dz=126] slot.armor.feet 0 loot "ench_armors/ench_protection2_chainmail_boots"
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"红保护等级"=2}] ~~~ loot replace entity @a[scores={"分队"=1,"防具等级"=3},x=-63,y=171,z=-63,dx=126,dy=33,dz=126] slot.armor.legs 0 loot "ench_armors/ench_protection2_iron_leggings"
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"红保护等级"=2}] ~~~ loot replace entity @a[scores={"分队"=1,"防具等级"=3},x=-63,y=171,z=-63,dx=126,dy=33,dz=126] slot.armor.feet 0 loot "ench_armors/ench_protection2_iron_boots"
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"红保护等级"=2}] ~~~ loot replace entity @a[scores={"分队"=1,"防具等级"=4},x=-63,y=171,z=-63,dx=126,dy=33,dz=126] slot.armor.legs 0 loot "ench_armors/ench_protection2_diamond_leggings"
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"红保护等级"=2}] ~~~ loot replace entity @a[scores={"分队"=1,"防具等级"=4},x=-63,y=171,z=-63,dx=126,dy=33,dz=126] slot.armor.feet 0 loot "ench_armors/ench_protection2_diamond_boots"
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"红保护等级"=3}] ~~~ loot replace entity @a[scores={"分队"=1},x=-63,y=171,z=-63,dx=126,dy=33,dz=126] slot.armor.head 0 loot "ench_armors/ench_protection3_red_team_helmet"
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"红保护等级"=3}] ~~~ loot replace entity @a[scores={"分队"=1},x=-63,y=171,z=-63,dx=126,dy=33,dz=126] slot.armor.chest 0 loot "ench_armors/ench_protection3_red_team_chestplate"
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"红保护等级"=3}] ~~~ loot replace entity @a[scores={"分队"=1,"防具等级"=1},x=-63,y=171,z=-63,dx=126,dy=33,dz=126] slot.armor.legs 0 loot "ench_armors/ench_protection3_red_team_leggings"
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"红保护等级"=3}] ~~~ loot replace entity @a[scores={"分队"=1,"防具等级"=1},x=-63,y=171,z=-63,dx=126,dy=33,dz=126] slot.armor.feet 0 loot "ench_armors/ench_protection3_red_team_boots"
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"红保护等级"=3}] ~~~ loot replace entity @a[scores={"分队"=1,"防具等级"=2},x=-63,y=171,z=-63,dx=126,dy=33,dz=126] slot.armor.legs 0 loot "ench_armors/ench_protection3_chainmail_leggings"
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"红保护等级"=3}] ~~~ loot replace entity @a[scores={"分队"=1,"防具等级"=2},x=-63,y=171,z=-63,dx=126,dy=33,dz=126] slot.armor.feet 0 loot "ench_armors/ench_protection3_chainmail_boots"
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"红保护等级"=3}] ~~~ loot replace entity @a[scores={"分队"=1,"防具等级"=3},x=-63,y=171,z=-63,dx=126,dy=33,dz=126] slot.armor.legs 0 loot "ench_armors/ench_protection3_iron_leggings"
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"红保护等级"=3}] ~~~ loot replace entity @a[scores={"分队"=1,"防具等级"=3},x=-63,y=171,z=-63,dx=126,dy=33,dz=126] slot.armor.feet 0 loot "ench_armors/ench_protection3_iron_boots"
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"红保护等级"=3}] ~~~ loot replace entity @a[scores={"分队"=1,"防具等级"=4},x=-63,y=171,z=-63,dx=126,dy=33,dz=126] slot.armor.legs 0 loot "ench_armors/ench_protection3_diamond_leggings"
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"红保护等级"=3}] ~~~ loot replace entity @a[scores={"分队"=1,"防具等级"=4},x=-63,y=171,z=-63,dx=126,dy=33,dz=126] slot.armor.feet 0 loot "ench_armors/ench_protection3_diamond_boots"
#蓝保护
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"蓝保护等级"=1}] ~~~ loot replace entity @a[scores={"分队"=2},x=-63,y=171,z=-63,dx=126,dy=33,dz=126] slot.armor.head 0 loot "ench_armors/ench_protection1_blue_team_helmet"
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"蓝保护等级"=1}] ~~~ loot replace entity @a[scores={"分队"=2},x=-63,y=171,z=-63,dx=126,dy=33,dz=126] slot.armor.chest 0 loot "ench_armors/ench_protection1_blue_team_chestplate"
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"蓝保护等级"=1}] ~~~ loot replace entity @a[scores={"分队"=2,"防具等级"=1},x=-63,y=171,z=-63,dx=126,dy=33,dz=126] slot.armor.legs 0 loot "ench_armors/ench_protection1_blue_team_leggings"
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"蓝保护等级"=1}] ~~~ loot replace entity @a[scores={"分队"=2,"防具等级"=1},x=-63,y=171,z=-63,dx=126,dy=33,dz=126] slot.armor.feet 0 loot "ench_armors/ench_protection1_blue_team_boots"
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"蓝保护等级"=1}] ~~~ loot replace entity @a[scores={"分队"=2,"防具等级"=2},x=-63,y=171,z=-63,dx=126,dy=33,dz=126] slot.armor.legs 0 loot "ench_armors/ench_protection1_chainmail_leggings"
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"蓝保护等级"=1}] ~~~ loot replace entity @a[scores={"分队"=2,"防具等级"=2},x=-63,y=171,z=-63,dx=126,dy=33,dz=126] slot.armor.feet 0 loot "ench_armors/ench_protection1_chainmail_boots"
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"蓝保护等级"=1}] ~~~ loot replace entity @a[scores={"分队"=2,"防具等级"=3},x=-63,y=171,z=-63,dx=126,dy=33,dz=126] slot.armor.legs 0 loot "ench_armors/ench_protection1_iron_leggings"
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"蓝保护等级"=1}] ~~~ loot replace entity @a[scores={"分队"=2,"防具等级"=3},x=-63,y=171,z=-63,dx=126,dy=33,dz=126] slot.armor.feet 0 loot "ench_armors/ench_protection1_iron_boots"
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"蓝保护等级"=1}] ~~~ loot replace entity @a[scores={"分队"=2,"防具等级"=4},x=-63,y=171,z=-63,dx=126,dy=33,dz=126] slot.armor.legs 0 loot "ench_armors/ench_protection1_diamond_leggings"
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"蓝保护等级"=1}] ~~~ loot replace entity @a[scores={"分队"=2,"防具等级"=4},x=-63,y=171,z=-63,dx=126,dy=33,dz=126] slot.armor.feet 0 loot "ench_armors/ench_protection1_diamond_boots"
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"蓝保护等级"=2}] ~~~ loot replace entity @a[scores={"分队"=2},x=-63,y=171,z=-63,dx=126,dy=33,dz=126] slot.armor.head 0 loot "ench_armors/ench_protection2_blue_team_helmet"
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"蓝保护等级"=2}] ~~~ loot replace entity @a[scores={"分队"=2},x=-63,y=171,z=-63,dx=126,dy=33,dz=126] slot.armor.chest 0 loot "ench_armors/ench_protection2_blue_team_chestplate"
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"蓝保护等级"=2}] ~~~ loot replace entity @a[scores={"分队"=2,"防具等级"=1},x=-63,y=171,z=-63,dx=126,dy=33,dz=126] slot.armor.legs 0 loot "ench_armors/ench_protection2_blue_team_leggings"
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"蓝保护等级"=2}] ~~~ loot replace entity @a[scores={"分队"=2,"防具等级"=1},x=-63,y=171,z=-63,dx=126,dy=33,dz=126] slot.armor.feet 0 loot "ench_armors/ench_protection2_blue_team_boots"
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"蓝保护等级"=2}] ~~~ loot replace entity @a[scores={"分队"=2,"防具等级"=2},x=-63,y=171,z=-63,dx=126,dy=33,dz=126] slot.armor.legs 0 loot "ench_armors/ench_protection2_chainmail_leggings"
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"蓝保护等级"=2}] ~~~ loot replace entity @a[scores={"分队"=2,"防具等级"=2},x=-63,y=171,z=-63,dx=126,dy=33,dz=126] slot.armor.feet 0 loot "ench_armors/ench_protection2_chainmail_boots"
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"蓝保护等级"=2}] ~~~ loot replace entity @a[scores={"分队"=2,"防具等级"=3},x=-63,y=171,z=-63,dx=126,dy=33,dz=126] slot.armor.legs 0 loot "ench_armors/ench_protection2_iron_leggings"
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"蓝保护等级"=2}] ~~~ loot replace entity @a[scores={"分队"=2,"防具等级"=3},x=-63,y=171,z=-63,dx=126,dy=33,dz=126] slot.armor.feet 0 loot "ench_armors/ench_protection2_iron_boots"
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"蓝保护等级"=2}] ~~~ loot replace entity @a[scores={"分队"=2,"防具等级"=4},x=-63,y=171,z=-63,dx=126,dy=33,dz=126] slot.armor.legs 0 loot "ench_armors/ench_protection2_diamond_leggings"
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"蓝保护等级"=2}] ~~~ loot replace entity @a[scores={"分队"=2,"防具等级"=4},x=-63,y=171,z=-63,dx=126,dy=33,dz=126] slot.armor.feet 0 loot "ench_armors/ench_protection2_diamond_boots"
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"蓝保护等级"=3}] ~~~ loot replace entity @a[scores={"分队"=2},x=-63,y=171,z=-63,dx=126,dy=33,dz=126] slot.armor.head 0 loot "ench_armors/ench_protection3_blue_team_helmet"
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"蓝保护等级"=3}] ~~~ loot replace entity @a[scores={"分队"=2},x=-63,y=171,z=-63,dx=126,dy=33,dz=126] slot.armor.chest 0 loot "ench_armors/ench_protection3_blue_team_chestplate"
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"蓝保护等级"=3}] ~~~ loot replace entity @a[scores={"分队"=2,"防具等级"=1},x=-63,y=171,z=-63,dx=126,dy=33,dz=126] slot.armor.legs 0 loot "ench_armors/ench_protection3_blue_team_leggings"
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"蓝保护等级"=3}] ~~~ loot replace entity @a[scores={"分队"=2,"防具等级"=1},x=-63,y=171,z=-63,dx=126,dy=33,dz=126] slot.armor.feet 0 loot "ench_armors/ench_protection3_blue_team_boots"
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"蓝保护等级"=3}] ~~~ loot replace entity @a[scores={"分队"=2,"防具等级"=2},x=-63,y=171,z=-63,dx=126,dy=33,dz=126] slot.armor.legs 0 loot "ench_armors/ench_protection3_chainmail_leggings"
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"蓝保护等级"=3}] ~~~ loot replace entity @a[scores={"分队"=2,"防具等级"=2},x=-63,y=171,z=-63,dx=126,dy=33,dz=126] slot.armor.feet 0 loot "ench_armors/ench_protection3_chainmail_boots"
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"蓝保护等级"=3}] ~~~ loot replace entity @a[scores={"分队"=2,"防具等级"=3},x=-63,y=171,z=-63,dx=126,dy=33,dz=126] slot.armor.legs 0 loot "ench_armors/ench_protection3_iron_leggings"
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"蓝保护等级"=3}] ~~~ loot replace entity @a[scores={"分队"=2,"防具等级"=3},x=-63,y=171,z=-63,dx=126,dy=33,dz=126] slot.armor.feet 0 loot "ench_armors/ench_protection3_iron_boots"
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"蓝保护等级"=3}] ~~~ loot replace entity @a[scores={"分队"=2,"防具等级"=4},x=-63,y=171,z=-63,dx=126,dy=33,dz=126] slot.armor.legs 0 loot "ench_armors/ench_protection3_diamond_leggings"
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"蓝保护等级"=3}] ~~~ loot replace entity @a[scores={"分队"=2,"防具等级"=4},x=-63,y=171,z=-63,dx=126,dy=33,dz=126] slot.armor.feet 0 loot "ench_armors/ench_protection3_diamond_boots"
#黄保护
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"黄保护等级"=1}] ~~~ loot replace entity @a[scores={"分队"=3},x=-63,y=171,z=-63,dx=126,dy=33,dz=126] slot.armor.head 0 loot "ench_armors/ench_protection1_blue_team_helmet"
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"黄保护等级"=1}] ~~~ loot replace entity @a[scores={"分队"=3},x=-63,y=171,z=-63,dx=126,dy=33,dz=126] slot.armor.chest 0 loot "ench_armors/ench_protection1_blue_team_chestplate"
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"黄保护等级"=1}] ~~~ loot replace entity @a[scores={"分队"=3,"防具等级"=1},x=-63,y=171,z=-63,dx=126,dy=33,dz=126] slot.armor.legs 0 loot "ench_armors/ench_protection1_blue_team_leggings"
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"黄保护等级"=1}] ~~~ loot replace entity @a[scores={"分队"=3,"防具等级"=1},x=-63,y=171,z=-63,dx=126,dy=33,dz=126] slot.armor.feet 0 loot "ench_armors/ench_protection1_blue_team_boots"
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"黄保护等级"=1}] ~~~ loot replace entity @a[scores={"分队"=3,"防具等级"=2},x=-63,y=171,z=-63,dx=126,dy=33,dz=126] slot.armor.legs 0 loot "ench_armors/ench_protection1_chainmail_leggings"
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"黄保护等级"=1}] ~~~ loot replace entity @a[scores={"分队"=3,"防具等级"=2},x=-63,y=171,z=-63,dx=126,dy=33,dz=126] slot.armor.feet 0 loot "ench_armors/ench_protection1_chainmail_boots"
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"黄保护等级"=1}] ~~~ loot replace entity @a[scores={"分队"=3,"防具等级"=3},x=-63,y=171,z=-63,dx=126,dy=33,dz=126] slot.armor.legs 0 loot "ench_armors/ench_protection1_iron_leggings"
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"黄保护等级"=1}] ~~~ loot replace entity @a[scores={"分队"=3,"防具等级"=3},x=-63,y=171,z=-63,dx=126,dy=33,dz=126] slot.armor.feet 0 loot "ench_armors/ench_protection1_iron_boots"
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"黄保护等级"=1}] ~~~ loot replace entity @a[scores={"分队"=3,"防具等级"=4},x=-63,y=171,z=-63,dx=126,dy=33,dz=126] slot.armor.legs 0 loot "ench_armors/ench_protection1_diamond_leggings"
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"黄保护等级"=1}] ~~~ loot replace entity @a[scores={"分队"=3,"防具等级"=4},x=-63,y=171,z=-63,dx=126,dy=33,dz=126] slot.armor.feet 0 loot "ench_armors/ench_protection1_diamond_boots"
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"黄保护等级"=2}] ~~~ loot replace entity @a[scores={"分队"=3},x=-63,y=171,z=-63,dx=126,dy=33,dz=126] slot.armor.head 0 loot "ench_armors/ench_protection2_blue_team_helmet"
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"黄保护等级"=2}] ~~~ loot replace entity @a[scores={"分队"=3},x=-63,y=171,z=-63,dx=126,dy=33,dz=126] slot.armor.chest 0 loot "ench_armors/ench_protection2_blue_team_chestplate"
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"黄保护等级"=2}] ~~~ loot replace entity @a[scores={"分队"=3,"防具等级"=1},x=-63,y=171,z=-63,dx=126,dy=33,dz=126] slot.armor.legs 0 loot "ench_armors/ench_protection2_blue_team_leggings"
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"黄保护等级"=2}] ~~~ loot replace entity @a[scores={"分队"=3,"防具等级"=1},x=-63,y=171,z=-63,dx=126,dy=33,dz=126] slot.armor.feet 0 loot "ench_armors/ench_protection2_blue_team_boots"
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"黄保护等级"=2}] ~~~ loot replace entity @a[scores={"分队"=3,"防具等级"=2},x=-63,y=171,z=-63,dx=126,dy=33,dz=126] slot.armor.legs 0 loot "ench_armors/ench_protection2_chainmail_leggings"
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"黄保护等级"=2}] ~~~ loot replace entity @a[scores={"分队"=3,"防具等级"=2},x=-63,y=171,z=-63,dx=126,dy=33,dz=126] slot.armor.feet 0 loot "ench_armors/ench_protection2_chainmail_boots"
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"黄保护等级"=2}] ~~~ loot replace entity @a[scores={"分队"=3,"防具等级"=3},x=-63,y=171,z=-63,dx=126,dy=33,dz=126] slot.armor.legs 0 loot "ench_armors/ench_protection2_iron_leggings"
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"黄保护等级"=2}] ~~~ loot replace entity @a[scores={"分队"=3,"防具等级"=3},x=-63,y=171,z=-63,dx=126,dy=33,dz=126] slot.armor.feet 0 loot "ench_armors/ench_protection2_iron_boots"
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"黄保护等级"=2}] ~~~ loot replace entity @a[scores={"分队"=3,"防具等级"=4},x=-63,y=171,z=-63,dx=126,dy=33,dz=126] slot.armor.legs 0 loot "ench_armors/ench_protection2_diamond_leggings"
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"黄保护等级"=2}] ~~~ loot replace entity @a[scores={"分队"=3,"防具等级"=4},x=-63,y=171,z=-63,dx=126,dy=33,dz=126] slot.armor.feet 0 loot "ench_armors/ench_protection2_diamond_boots"
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"黄保护等级"=3}] ~~~ loot replace entity @a[scores={"分队"=3},x=-63,y=171,z=-63,dx=126,dy=33,dz=126] slot.armor.head 0 loot "ench_armors/ench_protection3_blue_team_helmet"
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"黄保护等级"=3}] ~~~ loot replace entity @a[scores={"分队"=3},x=-63,y=171,z=-63,dx=126,dy=33,dz=126] slot.armor.chest 0 loot "ench_armors/ench_protection3_blue_team_chestplate"
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"黄保护等级"=3}] ~~~ loot replace entity @a[scores={"分队"=3,"防具等级"=1},x=-63,y=171,z=-63,dx=126,dy=33,dz=126] slot.armor.legs 0 loot "ench_armors/ench_protection3_blue_team_leggings"
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"黄保护等级"=3}] ~~~ loot replace entity @a[scores={"分队"=3,"防具等级"=1},x=-63,y=171,z=-63,dx=126,dy=33,dz=126] slot.armor.feet 0 loot "ench_armors/ench_protection3_blue_team_boots"
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"黄保护等级"=3}] ~~~ loot replace entity @a[scores={"分队"=3,"防具等级"=2},x=-63,y=171,z=-63,dx=126,dy=33,dz=126] slot.armor.legs 0 loot "ench_armors/ench_protection3_chainmail_leggings"
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"黄保护等级"=3}] ~~~ loot replace entity @a[scores={"分队"=3,"防具等级"=2},x=-63,y=171,z=-63,dx=126,dy=33,dz=126] slot.armor.feet 0 loot "ench_armors/ench_protection3_chainmail_boots"
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"黄保护等级"=3}] ~~~ loot replace entity @a[scores={"分队"=3,"防具等级"=3},x=-63,y=171,z=-63,dx=126,dy=33,dz=126] slot.armor.legs 0 loot "ench_armors/ench_protection3_iron_leggings"
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"黄保护等级"=3}] ~~~ loot replace entity @a[scores={"分队"=3,"防具等级"=3},x=-63,y=171,z=-63,dx=126,dy=33,dz=126] slot.armor.feet 0 loot "ench_armors/ench_protection3_iron_boots"
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"黄保护等级"=3}] ~~~ loot replace entity @a[scores={"分队"=3,"防具等级"=4},x=-63,y=171,z=-63,dx=126,dy=33,dz=126] slot.armor.legs 0 loot "ench_armors/ench_protection3_diamond_leggings"
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"黄保护等级"=3}] ~~~ loot replace entity @a[scores={"分队"=3,"防具等级"=4},x=-63,y=171,z=-63,dx=126,dy=33,dz=126] slot.armor.feet 0 loot "ench_armors/ench_protection3_diamond_boots"

#红锋利
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"红锋利等级"=1}] ~~~ tag @a[scores={"分队"=1},x=-63,y=171,z=-63,dx=126,dy=33,dz=126,tag=!have_upgraded_sword_sharpnessI] add clear_wooden_sword
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"红锋利等级"=1}] ~~~ tag @a[scores={"分队"=1},x=-63,y=171,z=-63,dx=126,dy=33,dz=126,tag=!have_upgraded_sword_sharpnessI] add clear_stone_sword
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"红锋利等级"=1}] ~~~ tag @a[scores={"分队"=1},x=-63,y=171,z=-63,dx=126,dy=33,dz=126,tag=!have_upgraded_sword_sharpnessI] add clear_iron_sword
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"红锋利等级"=1}] ~~~ tag @a[scores={"分队"=1},x=-63,y=171,z=-63,dx=126,dy=33,dz=126,tag=!have_upgraded_sword_sharpnessI] add clear_diamond_sword
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"红锋利等级"=1}] ~~~ tag @a[scores={"分队"=1,"剑等级"=1},x=-63,y=171,z=-63,dx=126,dy=33,dz=126,tag=!have_upgraded_sword_sharpnessI] add give_wooden_sword_sharpnessI
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"红锋利等级"=1}] ~~~ tag @a[scores={"分队"=1,"剑等级"=2},x=-63,y=171,z=-63,dx=126,dy=33,dz=126,tag=!have_upgraded_sword_sharpnessI] add give_stone_sword_sharpnessI
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"红锋利等级"=1}] ~~~ tag @a[scores={"分队"=1,"剑等级"=3},x=-63,y=171,z=-63,dx=126,dy=33,dz=126,tag=!have_upgraded_sword_sharpnessI] add give_iron_sword_sharpnessI
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"红锋利等级"=1}] ~~~ tag @a[scores={"分队"=1,"剑等级"=4},x=-63,y=171,z=-63,dx=126,dy=33,dz=126,tag=!have_upgraded_sword_sharpnessI] add give_diamond_sword_sharpnessI
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"红锋利等级"=1}] ~~~ tag @a[scores={"分队"=1}] add have_upgraded_sword_sharpnessI
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"红锋利等级"=2}] ~~~ tag @a[scores={"分队"=1},x=-63,y=171,z=-63,dx=126,dy=33,dz=126,tag=!have_upgraded_sword_sharpnessII] add clear_wooden_sword_sharpnessI
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"红锋利等级"=2}] ~~~ tag @a[scores={"分队"=1},x=-63,y=171,z=-63,dx=126,dy=33,dz=126,tag=!have_upgraded_sword_sharpnessII] add clear_stone_sword_sharpnessI
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"红锋利等级"=2}] ~~~ tag @a[scores={"分队"=1},x=-63,y=171,z=-63,dx=126,dy=33,dz=126,tag=!have_upgraded_sword_sharpnessII] add clear_iron_sword_sharpnessI
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"红锋利等级"=2}] ~~~ tag @a[scores={"分队"=1},x=-63,y=171,z=-63,dx=126,dy=33,dz=126,tag=!have_upgraded_sword_sharpnessII] add clear_diamond_sword_sharpnessI
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"红锋利等级"=2}] ~~~ tag @a[scores={"分队"=1,"剑等级"=1},x=-63,y=171,z=-63,dx=126,dy=33,dz=126,tag=!have_upgraded_sword_sharpnessII] add give_wooden_sword_sharpnessII 
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"红锋利等级"=2}] ~~~ tag @a[scores={"分队"=1,"剑等级"=2},x=-63,y=171,z=-63,dx=126,dy=33,dz=126,tag=!have_upgraded_sword_sharpnessII] add give_stone_sword_sharpnessII
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"红锋利等级"=2}] ~~~ tag @a[scores={"分队"=1,"剑等级"=3},x=-63,y=171,z=-63,dx=126,dy=33,dz=126,tag=!have_upgraded_sword_sharpnessII] add give_iron_sword_sharpnessII
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"红锋利等级"=2}] ~~~ tag @a[scores={"分队"=1,"剑等级"=4},x=-63,y=171,z=-63,dx=126,dy=33,dz=126,tag=!have_upgraded_sword_sharpnessII] add give_diamond_sword_sharpnessII
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"红锋利等级"=2}] ~~~ tag @a[scores={"分队"=1}] add have_upgraded_sword_sharpnessII
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"红锋利等级"=3}] ~~~ tag @a[scores={"分队"=1},x=-63,y=171,z=-63,dx=126,dy=33,dz=126,tag=!have_upgraded_sword_sharpnessIII] add clear_wooden_sword_sharpnessII
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"红锋利等级"=3}] ~~~ tag @a[scores={"分队"=1},x=-63,y=171,z=-63,dx=126,dy=33,dz=126,tag=!have_upgraded_sword_sharpnessIII] add clear_stone_sword_sharpnessII
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"红锋利等级"=3}] ~~~ tag @a[scores={"分队"=1},x=-63,y=171,z=-63,dx=126,dy=33,dz=126,tag=!have_upgraded_sword_sharpnessIII] add clear_iron_sword_sharpnessII
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"红锋利等级"=3}] ~~~ tag @a[scores={"分队"=1},x=-63,y=171,z=-63,dx=126,dy=33,dz=126,tag=!have_upgraded_sword_sharpnessIII] add clear_diamond_sword_sharpnessII
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"红锋利等级"=3}] ~~~ tag @a[scores={"分队"=1,"剑等级"=1},x=-63,y=171,z=-63,dx=126,dy=33,dz=126,tag=!have_upgraded_sword_sharpnessIII] add give_wooden_sword_sharpnessIII 
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"红锋利等级"=3}] ~~~ tag @a[scores={"分队"=1,"剑等级"=2},x=-63,y=171,z=-63,dx=126,dy=33,dz=126,tag=!have_upgraded_sword_sharpnessIII] add give_stone_sword_sharpnessIII
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"红锋利等级"=3}] ~~~ tag @a[scores={"分队"=1,"剑等级"=3},x=-63,y=171,z=-63,dx=126,dy=33,dz=126,tag=!have_upgraded_sword_sharpnessIII] add give_iron_sword_sharpnessIII
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"红锋利等级"=3}] ~~~ tag @a[scores={"分队"=1,"剑等级"=4},x=-63,y=171,z=-63,dx=126,dy=33,dz=126,tag=!have_upgraded_sword_sharpnessIII] add give_diamond_sword_sharpnessIII
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"红锋利等级"=3}] ~~~ tag @a[scores={"分队"=1}] add have_upgraded_sword_sharpnessIII
#蓝锋利
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"蓝锋利等级"=1}] ~~~ tag @a[scores={"分队"=2},x=-63,y=171,z=-63,dx=126,dy=33,dz=126,tag=!have_upgraded_sword_sharpnessI] add clear_wooden_sword
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"蓝锋利等级"=1}] ~~~ tag @a[scores={"分队"=2},x=-63,y=171,z=-63,dx=126,dy=33,dz=126,tag=!have_upgraded_sword_sharpnessI] add clear_stone_sword
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"蓝锋利等级"=1}] ~~~ tag @a[scores={"分队"=2},x=-63,y=171,z=-63,dx=126,dy=33,dz=126,tag=!have_upgraded_sword_sharpnessI] add clear_iron_sword
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"蓝锋利等级"=1}] ~~~ tag @a[scores={"分队"=2},x=-63,y=171,z=-63,dx=126,dy=33,dz=126,tag=!have_upgraded_sword_sharpnessI] add clear_diamond_sword
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"蓝锋利等级"=1}] ~~~ tag @a[scores={"分队"=2,"剑等级"=1},x=-63,y=171,z=-63,dx=126,dy=33,dz=126,tag=!have_upgraded_sword_sharpnessI] add give_wooden_sword_sharpnessI 
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"蓝锋利等级"=1}] ~~~ tag @a[scores={"分队"=2,"剑等级"=2},x=-63,y=171,z=-63,dx=126,dy=33,dz=126,tag=!have_upgraded_sword_sharpnessI] add give_stone_sword_sharpnessI
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"蓝锋利等级"=1}] ~~~ tag @a[scores={"分队"=2,"剑等级"=3},x=-63,y=171,z=-63,dx=126,dy=33,dz=126,tag=!have_upgraded_sword_sharpnessI] add give_iron_sword_sharpnessI
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"蓝锋利等级"=1}] ~~~ tag @a[scores={"分队"=2,"剑等级"=4},x=-63,y=171,z=-63,dx=126,dy=33,dz=126,tag=!have_upgraded_sword_sharpnessI] add give_diamond_sword_sharpnessI
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"蓝锋利等级"=1}] ~~~ tag @a[scores={"分队"=2}] add have_upgraded_sword_sharpnessI
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"蓝锋利等级"=2}] ~~~ tag @a[scores={"分队"=2},x=-63,y=171,z=-63,dx=126,dy=33,dz=126,tag=!have_upgraded_sword_sharpnessII] add clear_wooden_sword_sharpnessI
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"蓝锋利等级"=2}] ~~~ tag @a[scores={"分队"=2},x=-63,y=171,z=-63,dx=126,dy=33,dz=126,tag=!have_upgraded_sword_sharpnessII] add clear_stone_sword_sharpnessI
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"蓝锋利等级"=2}] ~~~ tag @a[scores={"分队"=2},x=-63,y=171,z=-63,dx=126,dy=33,dz=126,tag=!have_upgraded_sword_sharpnessII] add clear_iron_sword_sharpnessI
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"蓝锋利等级"=2}] ~~~ tag @a[scores={"分队"=2},x=-63,y=171,z=-63,dx=126,dy=33,dz=126,tag=!have_upgraded_sword_sharpnessII] add clear_diamond_sword_sharpnessI
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"蓝锋利等级"=2}] ~~~ tag @a[scores={"分队"=2,"剑等级"=1},x=-63,y=171,z=-63,dx=126,dy=33,dz=126,tag=!have_upgraded_sword_sharpnessII] add give_wooden_sword_sharpnessII 
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"蓝锋利等级"=2}] ~~~ tag @a[scores={"分队"=2,"剑等级"=2},x=-63,y=171,z=-63,dx=126,dy=33,dz=126,tag=!have_upgraded_sword_sharpnessII] add give_stone_sword_sharpnessII
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"蓝锋利等级"=2}] ~~~ tag @a[scores={"分队"=2,"剑等级"=3},x=-63,y=171,z=-63,dx=126,dy=33,dz=126,tag=!have_upgraded_sword_sharpnessII] add give_iron_sword_sharpnessII
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"蓝锋利等级"=2}] ~~~ tag @a[scores={"分队"=2,"剑等级"=4},x=-63,y=171,z=-63,dx=126,dy=33,dz=126,tag=!have_upgraded_sword_sharpnessII] add give_diamond_sword_sharpnessII
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"蓝锋利等级"=2}] ~~~ tag @a[scores={"分队"=2}] add have_upgraded_sword_sharpnessII
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"蓝锋利等级"=3}] ~~~ tag @a[scores={"分队"=2},x=-63,y=171,z=-63,dx=126,dy=33,dz=126,tag=!have_upgraded_sword_sharpnessIII] add clear_wooden_sword_sharpnessII
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"蓝锋利等级"=3}] ~~~ tag @a[scores={"分队"=2},x=-63,y=171,z=-63,dx=126,dy=33,dz=126,tag=!have_upgraded_sword_sharpnessIII] add clear_stone_sword_sharpnessII
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"蓝锋利等级"=3}] ~~~ tag @a[scores={"分队"=2},x=-63,y=171,z=-63,dx=126,dy=33,dz=126,tag=!have_upgraded_sword_sharpnessIII] add clear_iron_sword_sharpnessII
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"蓝锋利等级"=3}] ~~~ tag @a[scores={"分队"=2},x=-63,y=171,z=-63,dx=126,dy=33,dz=126,tag=!have_upgraded_sword_sharpnessIII] add clear_diamond_sword_sharpnessII
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"蓝锋利等级"=3}] ~~~ tag @a[scores={"分队"=2,"剑等级"=1},x=-63,y=171,z=-63,dx=126,dy=33,dz=126,tag=!have_upgraded_sword_sharpnessIII] add give_wooden_sword_sharpnessIII 
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"蓝锋利等级"=3}] ~~~ tag @a[scores={"分队"=2,"剑等级"=2},x=-63,y=171,z=-63,dx=126,dy=33,dz=126,tag=!have_upgraded_sword_sharpnessIII] add give_stone_sword_sharpnessIII
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"蓝锋利等级"=3}] ~~~ tag @a[scores={"分队"=2,"剑等级"=3},x=-63,y=171,z=-63,dx=126,dy=33,dz=126,tag=!have_upgraded_sword_sharpnessIII] add give_iron_sword_sharpnessIII
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"蓝锋利等级"=3}] ~~~ tag @a[scores={"分队"=2,"剑等级"=4},x=-63,y=171,z=-63,dx=126,dy=33,dz=126,tag=!have_upgraded_sword_sharpnessIII] add give_diamond_sword_sharpnessIII
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"蓝锋利等级"=3}] ~~~ tag @a[scores={"分队"=2}] add have_upgraded_sword_sharpnessIII
