#红队陷阱被触发
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"红陷阱等级"=1..3}] ~~~ execute @e[type=player,scores={"分队"=2},x=-5,y=176,z=32,dx=10,dy=22,dz=26] ~~~ title @a[scores={"分队"=1}] title §c§lTeam trap is triggered
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"红陷阱等级"=1..3}] ~~~ execute @e[type=player,scores={"分队"=2},x=-5,y=176,z=32,dx=10,dy=22,dz=26] ~~~ tellraw @a[scores={"分队"=1}] { "rawtext" : [ { "text" : "§lBED WARS >> §c§lAn enemy player is near your bed and the team trap has been triggered!" } ] }
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"红陷阱等级"=1..3}] ~~~ execute @e[type=player,scores={"分队"=2},x=-5,y=176,z=32,dx=10,dy=22,dz=26] ~~~ playsound mob.endermen.portal @a[scores={"分队"=1}]
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"红陷阱等级"=1}] ~~~ execute @e[type=player,scores={"分队"=2},x=-5,y=176,z=32,dx=10,dy=22,dz=26] ~~~ tellraw @s { "rawtext" : [ { "text" : "§c§lyou triggered a trap!" } ] }
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"红陷阱等级"=1}] ~~~ execute @e[type=player,scores={"分队"=2},x=-5,y=176,z=32,dx=10,dy=22,dz=26] ~~~ effect @s mining_fatigue 10 0
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"红陷阱等级"=2}] ~~~ execute @e[type=player,scores={"分队"=2},x=-5,y=176,z=32,dx=10,dy=22,dz=26] ~~~ effect @s mining_fatigue 10 1
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"红陷阱等级"=3}] ~~~ execute @e[type=player,scores={"分队"=2},x=-5,y=176,z=32,dx=10,dy=22,dz=26] ~~~ effect @s mining_fatigue 10 1
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"红陷阱等级"=3}] ~~~ execute @e[type=player,scores={"分队"=2},x=-5,y=176,z=32,dx=10,dy=22,dz=26] ~~~ effect @s blindness 10 0
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"红陷阱等级"=1..3}] ~~~ execute @e[type=player,scores={"分队"=2},x=-5,y=176,z=32,dx=10,dy=22,dz=26] ~~~ scoreboard players set @e[type=armor_stand,name=main,scores={gameSTART=1}] "红陷阱等级" 0