function refresh_map/sign/red/forge
function refresh_map/sign/red/maniac_miner
function refresh_map/sign/red/protection
function refresh_map/sign/red/sharpness
function refresh_map/sign/red/trap
function refresh_map/sign/blue/forge
function refresh_map/sign/blue/maniac_miner
function refresh_map/sign/blue/protection
function refresh_map/sign/blue/sharpness
function refresh_map/sign/blue/trap
function refresh_map/sign/yellow/forge
function refresh_map/sign/yellow/maniac_miner
function refresh_map/sign/yellow/protection
function refresh_map/sign/yellow/sharpness
function refresh_map/sign/yellow/trap
function refresh_map/sign/green/forge
function refresh_map/sign/green/maniac_miner
function refresh_map/sign/green/protection
function refresh_map/sign/green/sharpness
function refresh_map/sign/green/trap